/* eslint-disable */export default Object.freeze({
    "stageid": "B100",
    "stagename": "Faron Woods: Forest Boss (R00 Ghirahim)",
    "maxx": 1460.0,
    "minx": -1460.0,
    "maxz": 400.0,
    "minz": -4250.0,
    "usedLayers": [
        0,
        1,
        2,
        3,
        4,
        5,
        13
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 980.0,
            "posy": 0.0,
            "posz": -3400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -2920.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 980.0,
            "posy": 0.0,
            "posz": -480.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -980.0,
            "posy": 0.0,
            "posz": -480.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -940.0,
            "posy": 0.0,
            "posz": -3410.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -50.0,
            "posz": 400.0,
            "sizex": 600.0,
            "sizey": 500.0,
            "sizez": 400.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 06",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "6F FF FF 01",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -50.0,
            "posz": -4200.0,
            "sizex": 600.0,
            "sizey": 500.0,
            "sizez": 400.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 07",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF 65",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "TgDefea",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 89 FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 09",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF BF FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0A",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF BC FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0B",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 80 FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0C",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED C6 33",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 66 65",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF C2 C0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "BGh",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "60 8A D3 F3",
            "unk2": "FF 1F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -700.0,
            "event_flag": 101,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 6657,
            "unk3": "FC 13",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 692,
                "untrigstoryfid": 772,
                "trigstoryf": "(not implemented yet -- 7771)",
                "untrigstoryf": "",
                "trigscenefid": 255,
                "untrigscenefid": 101,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0xD 20"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF D9 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "01 FF FF 01",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65381,
            "unk3": "FC 14",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "02 C0 FF 02",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65381,
            "unk3": "FC 15",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "03 C2 FF 03",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65381,
            "unk3": "FC 16",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF 65 63 03",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -100.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF 04",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -50.0,
            "posz": -4250.0,
            "sizex": 600.0,
            "sizey": 500.0,
            "sizez": 400.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 18",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED C6 33",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 66 65",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF D9 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED C6 B3",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 66 DF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "26 FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "26 FF FF FF",
            "posx": -300.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 5461,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "26 FF FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 60075,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "0B FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "0B FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF F7 C0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FD F0",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "DieTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF 70 6B 02",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF 64 01 00",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "sizex": 2250.0,
            "sizey": 2250.0,
            "sizez": 2250.0,
            "event_flag": 1,
            "transition_type": 223,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "PltChg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "3C 64 00 01",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "sizex": 2250.0,
            "sizey": 2250.0,
            "sizez": 2250.0,
            "event_flag": 0,
            "transition_type": 223,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "PltChg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF DF 70 04",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 4250.0,
            "sizey": 1600.0,
            "sizez": 4250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED C6 33",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF 66 65",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "0B FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "0B FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF D9 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 4,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF C2 C0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "BGh",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED CF E3",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF D9 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF FF 03",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "TgSBG",
            "type": "STAG",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "01 FF FF 01",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 13",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "02 C0 FF 02",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 14",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "03 C2 FF 03",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -200.0,
            "posz": -1950.0,
            "sizex": 1800.0,
            "sizey": 1600.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 15",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 5,
            "stageid": "B100"
        },
        {
            "unk1": "FF ED C6 33",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 13,
            "stageid": "B100"
        },
        {
            "unk1": "FF FF D9 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 13,
            "stageid": "B100"
        }
    ]
});