/* eslint-disable */export default Object.freeze({
    "stageid": "B100",
    "stagename": "Faron Woods: Forest Boss (R00 Ghirahim)",
    "maxx": 1460.0,
    "minx": -1460.0,
    "maxz": 100.0,
    "minz": -3950.0,
    "usedLayers": [
        0,
        1,
        2,
        3,
        4,
        5,
        13
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 980.0,
            "posy": 0.0,
            "posz": -3400.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -2920.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 980.0,
            "posy": 0.0,
            "posz": -480.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -980.0,
            "posy": 0.0,
            "posz": -480.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -940.0,
            "posy": 0.0,
            "posz": -3410.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -58,
            "byte4": 51,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 102,
            "byte4": 101,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -62,
            "byte4": -64,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "BGh",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 96,
            "tosky_scen_link": -118,
            "scen_link": -45,
            "byte4": -13,
            "unk1": "FF 1F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -700.0,
            "event_flag": 101,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 6657,
            "unk3": "FC 13",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -39,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -58,
            "byte4": 51,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 102,
            "byte4": 101,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -39,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -58,
            "byte4": -77,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 102,
            "byte4": -33,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "26 FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "26 FF FF FF",
            "posx": -300.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "15 55",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "26 FF FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "EA AB",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "ESf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -9,
            "byte4": -64,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -58,
            "byte4": 51,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 102,
            "byte4": 101,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -39,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -62,
            "byte4": -64,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "BGh",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -49,
            "byte4": -29,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": 1460.0,
            "posy": 0.0,
            "posz": -960.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "04 FF FF FF",
            "posx": -1460.0,
            "posy": 0.0,
            "posz": -2870.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -39,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -19,
            "scen_link": -58,
            "byte4": 51,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -3950.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 13
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -39,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 13
        }
    ]
});