/* eslint-disable */export default Object.freeze({
    "stageid": "B101_1",
    "stagename": "Faron Woods: Farore's Candle Room",
    "maxx": 1160.0,
    "minx": -2253.20166015625,
    "maxz": 1144.1717529296875,
    "minz": -2348.315185546875,
    "usedLayers": [
        0,
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF F0 56",
            "unk2": "FF FF FF FF",
            "posx": 1.281736969947815,
            "posy": 179.2956085205078,
            "posz": -1994.2569580078125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "SdCdl",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -580.0,
            "posy": 660.0,
            "posz": -1610.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 580.0,
            "posy": 660.0,
            "posz": -1610.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1160.0,
            "posy": 560.0,
            "posz": -600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 1160.0,
            "posy": 560.0,
            "posz": -600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 580.0,
            "posy": 560.0,
            "posz": 410.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -580.0,
            "posy": 560.0,
            "posz": 410.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF F4 C1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 840.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF F5 60",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "GodMark",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 4.725067138671875,
            "posy": 0.0,
            "posz": 1144.1717529296875,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 09",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "B2 FF 0E FF",
            "unk2": "FF FF FF FF",
            "posx": -2253.20166015625,
            "posy": 1335.598876953125,
            "posz": -2348.315185546875,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "TlpTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "56 03 FF 02",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -500.0,
            "posz": -600.0,
            "sizex": 5000.0,
            "sizey": 2000.0,
            "sizez": 5000.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 64070,
            "unk3": "FC 0B",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "00 FF 58 F1",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 1500.0,
            "posz": -500.0,
            "sizex": 7000.0,
            "sizey": 7000.0,
            "sizez": 7000.0,
            "event_flag": 255,
            "transition_type": 1,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Kytag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101_1"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF 1F FF FF",
            "posx": 285.5881042480469,
            "posy": 80.0,
            "posz": -570.83544921875,
            "event_flag": 88,
            "transition_type": 87,
            "angle": 65535,
            "talk_behaviour": 20220,
            "unk3": "FC 0D",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 87,
                "untrigscenefid": 88,
                "trigscenef": "scene flag: 0xB 80",
                "untrigscenef": "scene flag: 0xA 01"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101_1"
        },
        {
            "unk1": "F5 6F FF F3",
            "unk2": "FF 5F 02 46",
            "posx": -468.35760498046875,
            "posy": 120.0,
            "posz": -1110.455810546875,
            "event_flag": 255,
            "transition_type": 87,
            "angle": 0,
            "talk_behaviour": 65036,
            "unk3": "FC 0E",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 86,
                "spawnscenef": "scene flag: 0xB 40",
                "trigscenefid": 87,
                "trigscenef": "scene flag: 0xB 80",
                "itemid": 12,
                "chestid": 127,
                "item": "Goddess Longsword (shows a green rupee)"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101_1"
        }
    ]
});