/* eslint-disable */export default Object.freeze({
    "stageid": "B101",
    "stagename": "Faron Woods: Forest Boss (Asura)",
    "maxx": 3354.783447265625,
    "minx": -3159.857666015625,
    "maxz": 2517.388916015625,
    "minz": -2507.389404296875,
    "usedLayers": [
        0,
        1,
        2,
        3,
        6
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF D2 CB",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "BAsura",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 485.9230651855469,
            "posy": 0.0,
            "posz": -1300.703369140625,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -481.014892578125,
            "posy": 0.0,
            "posz": -1285.978515625,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -1290.8865966796875,
            "posy": 0.0,
            "posz": -481.0150451660156,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -1295.794921875,
            "posy": 0.0,
            "posz": 490.8312683105469,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -476.1063232421875,
            "posy": 0.0,
            "posz": 1295.794677734375,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 485.9232177734375,
            "posy": 0.0,
            "posz": 1305.611328125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 1285.9786376953125,
            "posy": 0.0,
            "posz": 495.739501953125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 1290.88671875,
            "posy": 0.0,
            "posz": -485.9233093261719,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "AsuraP",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 1000.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "60 EA D3 F3",
            "unk2": "FF 1F FF FF",
            "posx": -2279.2978515625,
            "posy": 612.003662109375,
            "posz": -2347.268798828125,
            "event_flag": 76,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 6660,
            "unk3": "FC 0A",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 692,
                "untrigstoryfid": 775,
                "trigstoryf": "(not implemented yet -- 7771)",
                "untrigstoryf": "",
                "trigscenefid": 255,
                "untrigscenefid": 76,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0x8 10",
                "eventSrc": "006-6KenseiNormal.c#L508"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 5F FF FF",
            "posx": -1.6839580535888672,
            "posy": 0.0,
            "posz": 2517.388916015625,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0B",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF 01",
            "unk2": "FF 5F FF FF",
            "posx": 14.157946586608887,
            "posy": 0.0,
            "posz": -2507.389404296875,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0C",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF CB FF 01",
            "unk2": "FF DF FF FF",
            "posx": 7.645709991455078,
            "posy": -80.0,
            "posz": 11.163154602050781,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0D",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FE 05 11 4C",
            "unk2": "FF FF FF FF",
            "posx": 3354.783447265625,
            "posy": 504.757568359375,
            "posz": 6.30974006652832,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "TgDefea",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF CC FF 03",
            "unk2": "FF DF FF FF",
            "posx": 39.40005111694336,
            "posy": -80.0,
            "posz": 11.163154602050781,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0F",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF CD FF 04",
            "unk2": "FF DF FF FF",
            "posx": 44.70939636230469,
            "posy": -80.0,
            "posz": 21.779855728149414,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 10",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "0F CE FF 03",
            "unk2": "FF DF FF FF",
            "posx": 44.70938491821289,
            "posy": -80.0,
            "posz": 1.9694969654083252,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 11",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF 60",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -100.0,
            "posz": 0.0,
            "sizex": 4500.0,
            "sizey": 2000.0,
            "sizez": 4500.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 12",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF 11",
            "unk2": "FF 1F FF FF",
            "posx": -3159.857666015625,
            "posy": 582.273681640625,
            "posz": 273.7790832519531,
            "event_flag": 193,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 20230,
            "unk3": "FC 14",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 193,
                "trigscenef": "no flag",
                "untrigscenef": "temp flag: 0x9 02",
                "eventSrc": "202-ForestD2.c#L27"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF F4 C1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "51 1F FC FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 20230,
            "unk3": "FC 16",
            "name": "NpcGhm",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 648,
                "trigstoryf": "-",
                "untrigstoryf": "Koloktos defeated",
                "eventSrc": "202-ForestD2.c#L27"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF 4D 4C",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "FF FD 5C 00",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "ShtCS",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "0A 4C FF 02",
            "unk2": "FF DF FF FF",
            "posx": 23.475994110107422,
            "posy": -80.0,
            "posz": 11.163154602050781,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 18",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B101"
        },
        {
            "unk1": "FF FD 64 00",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "ShtCS",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF FF FF FF",
            "posx": -2569.09375,
            "posy": 2002.205078125,
            "posz": -2346.422119140625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "TgSBG",
            "type": "STAG",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF F4 C1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF 4D 4C",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B101"
        },
        {
            "unk1": "FF FD 5C 00",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "ShtCS",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B101"
        },
        {
            "unk1": "0A 4C FF 02",
            "unk2": "FF DF FF FF",
            "posx": 7.581597805023193,
            "posy": -80.0,
            "posz": 11.163155555725098,
            "sizex": 3000.0,
            "sizey": 2000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 16",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B101"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 1016.2705078125,
            "posy": 0.0,
            "posz": 1023.85498046875,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "AsuraS",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6,
            "stageid": "B101"
        }
    ]
});