/* eslint-disable */export default Object.freeze({
    "stageid": "B201",
    "stagename": "Eldin Volcano: Volcano D2 Boss (Ghirahim 2nd Fight)",
    "maxx": 100.0,
    "minx": 0,
    "maxz": 2350.0,
    "minz": -2288.699951171875,
    "usedLayers": [
        "l1",
        "l13",
        "l2",
        "l3"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 124,
            "byte4": 125,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -9,
            "byte4": -48,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2288.699951171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -62,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "BGh2",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 97,
            "tosky_scen_link": 42,
            "scen_link": -45,
            "byte4": -13,
            "unk1": "FF 1F FF FF",
            "posx": 100.0,
            "posy": 0.0,
            "posz": 300.0,
            "event_flag": 125,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 6662,
            "unk3": "FC 08",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -49,
            "byte4": 68,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2350.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -9,
            "byte4": -48,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2288.699951171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 124,
            "byte4": 125,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -49,
            "byte4": 68,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2350.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -62,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "BGh2",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -32,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2288.699951171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -49,
            "byte4": 68,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2350.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -9,
            "byte4": -48,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -2288.699951171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l13"
        }
    ]
});