/* eslint-disable */export default Object.freeze({
    "stageid": "B201_1",
    "stagename": "Eldin Volcano: Volcano D2 Boss (Din's Fire)",
    "maxx": 1160.0,
    "minx": -1160.0,
    "maxz": 840.0,
    "minz": -2000.0,
    "usedLayers": [
        0
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -14,
            "byte4": 95,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 179.2956085205078,
            "posz": -2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "SdCdl",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -1160.0,
            "posy": 560.0,
            "posz": -600.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -580.0,
            "posy": 660.0,
            "posz": -1610.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -580.0,
            "posy": 560.0,
            "posz": 410.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 580.0,
            "posy": 560.0,
            "posz": 410.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1160.0,
            "posy": 560.0,
            "posz": -600.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 580.0,
            "posy": 660.0,
            "posz": -1610.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -11,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "GodMark",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -9,
            "byte4": -48,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 840.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        }
    ]
});