/* eslint-disable */export default Object.freeze({
    "stageid": "B210",
    "stagename": "Eldin Volcano: Volcano D1 Boss (Earth Spring)",
    "maxx": 7280.0,
    "minx": -2900.0,
    "maxz": 2760.0,
    "minz": -2620.0,
    "usedLayers": [
        0,
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 1570.0,
            "posy": 480.0,
            "posz": -390.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 1570.0,
            "posy": 480.0,
            "posz": 360.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -369.510009765625,
            "posy": 458.739990234375,
            "posz": -271.8800048828125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1563.0799560546875,
            "posy": 458.739990234375,
            "posz": -271.7799987792969,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1563.0799560546875,
            "posy": 458.739990234375,
            "posz": 271.7799987792969,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -2170.206787109375,
            "posy": 458.739990234375,
            "posz": -271.8800048828125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -2170.206787109375,
            "posy": 458.739990234375,
            "posz": 271.7799987792969,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -968.4199829101562,
            "posy": 458.739990234375,
            "posz": 271.7799987792969,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF 1F FF FF",
            "posx": 4700.0,
            "posy": 480.1500244140625,
            "posz": -200.0,
            "event_flag": 39,
            "transition_type": 38,
            "angle": 65280,
            "talk_behaviour": 30103,
            "unk3": "FC 09",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 38,
                "untrigscenefid": 39,
                "trigscenef": "scene flag: 0x5 40",
                "untrigscenef": "scene flag: 0x5 80"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 03 26",
            "unk2": "FF FF FF FF",
            "posx": 5700.0,
            "posy": 850.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "SngGS",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF F2 43",
            "unk2": "FF FF FF FF",
            "posx": -2335.0,
            "posy": 90.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "SldDoor",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 4800.0,
            "posy": 424.0500183105469,
            "posz": 400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 49152,
            "talk_behaviour": 65203,
            "unk3": "FC 08",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 179,
                "chestid": 127,
                "item": "Amber Tablet"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 00 01",
            "unk2": "FF 5F FF FF",
            "posx": -2900.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1000.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0C",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF AA FF",
            "unk2": "FF 5F FF FF",
            "posx": 2500.0,
            "posy": -100.0,
            "posz": 0.0,
            "sizex": 11000.0,
            "sizey": 4000.0,
            "sizez": 7000.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0D",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "C0 03 FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 2000.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 12000.0,
            "sizey": 3000.0,
            "sizez": 7000.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0E",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": -1050.0,
            "posy": 60.0,
            "posz": -1450.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 120.0,
            "posy": 60.0,
            "posz": -1250.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 64626,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 4820.0,
            "posy": 430.0,
            "posz": -2620.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 6500.0,
            "posy": 430.0,
            "posz": -1850.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 57344,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 7280.0,
            "posy": 430.0,
            "posz": -600.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 57344,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 7080.0,
            "posy": 430.0,
            "posz": 560.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 43691,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 6225.0,
            "posy": 430.0,
            "posz": 1800.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 40960,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 4880.0,
            "posy": 430.0,
            "posz": 2750.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 120.0,
            "posy": 60.0,
            "posz": 1450.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 34589,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": -1050.0,
            "posy": 60.0,
            "posz": 1350.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 29127,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": -1020.0,
            "posy": -90.0,
            "posz": 1340.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 61896,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 140.0,
            "posy": -90.0,
            "posz": 1440.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 1820,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 1480.0,
            "posy": -90.0,
            "posz": 980.0,
            "sizex": 550.0,
            "sizey": 400.0,
            "sizez": 250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 130.0,
            "posy": -90.0,
            "posz": -1240.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 64626,
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": -1030.0,
            "posy": -90.0,
            "posz": -1420.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 1480.0,
            "posy": -90.0,
            "posz": -970.0,
            "sizex": 550.0,
            "sizey": 400.0,
            "sizez": 250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 4820.0,
            "posy": 270.0,
            "posz": -2620.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 6520.0,
            "posy": 270.0,
            "posz": -1880.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 57344,
            "talk_behaviour": 0,
            "unk3": "FC 20",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 7280.0,
            "posy": 270.0,
            "posz": -630.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 56434,
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 7080.0,
            "posy": 270.0,
            "posz": 560.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 43691,
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 6230.0,
            "posy": 270.0,
            "posz": 1800.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 40960,
            "talk_behaviour": 0,
            "unk3": "FC 23",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF C5",
            "unk2": "FF FF FF FF",
            "posx": 4890.0,
            "posy": 270.0,
            "posz": 2760.0,
            "sizex": 350.0,
            "sizey": 400.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 24",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 1393.9500732421875,
            "posy": 60.0,
            "posz": -970.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF 01 04",
            "unk2": "FF FF FF FF",
            "posx": 1393.9500732421875,
            "posy": 60.0,
            "posz": 980.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 26",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -2170.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 300.0,
            "sizey": 400.0,
            "sizez": 200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 27",
            "name": "AttTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B210"
        },
        {
            "unk1": "FF FF D6 85",
            "unk2": "FF FF FF FF",
            "posx": 6800.0,
            "posy": 425.0500183105469,
            "posz": 0.0,
            "sizex": 800.0,
            "sizey": 150.0,
            "sizez": 800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 8192,
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "FairyTa",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B210"
        }
    ]
});