/* eslint-disable */export default Object.freeze({
    "stageid": "B300",
    "stagename": "Lanayru Desert: Desert Boss 00 (Moldarach)",
    "maxx": 2150.213623046875,
    "minx": -1798.712890625,
    "maxz": 2213.28759765625,
    "minz": -2899.91943359375,
    "usedLayers": [
        0,
        1,
        2,
        3
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "BMg",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "60 CA D3 F3",
            "unk2": "FF 1F FF FF",
            "posx": 5.0,
            "posy": 0.0,
            "posz": -775.0,
            "event_flag": 125,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 6659,
            "unk3": "FC 03",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 692,
                "untrigstoryfid": 774,
                "trigstoryf": "(not implemented yet -- 7771)",
                "untrigstoryf": "",
                "trigscenefid": 255,
                "untrigscenefid": 125,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0xE 20"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF E3",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -1.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "ODesert",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF D9 C2",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 2150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "DoorBs",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF F7 D3",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -1800.0,
            "posz": -2350.0,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "SldDoor",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -400.0,
            "posz": 4.598278045654297,
            "sizex": 2400.0,
            "sizey": 2000.0,
            "sizez": 2400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 05",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF 05 01",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -400.0,
            "posz": 4.598278045654297,
            "sizex": 2400.0,
            "sizey": 2000.0,
            "sizez": 2400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 06",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "C7 BF F7 D0",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": -400.0,
            "posz": 0.0,
            "sizex": 5000.0,
            "sizey": 5000.0,
            "sizez": 5000.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "DieTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "F0 5F 5F 3D",
            "unk2": "FF FF FF FF",
            "posx": 2150.213623046875,
            "posy": 198.01980590820312,
            "posz": 2213.28759765625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "SwTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF 00 FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 2.805450916290283,
            "posy": -1904.0986328125,
            "posz": -2899.91943359375,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1000.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 09",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FE 08 A7 78",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "TgDefea",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF 5F FF FF",
            "posx": -9.908405303955078,
            "posy": -1.0,
            "posz": 1509.977294921875,
            "sizex": 1000.0,
            "sizey": 500.0,
            "sizez": 1000.0,
            "event_flag": 252,
            "transition_type": 62,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0B",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -719.4788208007812,
            "posy": 0.0,
            "posz": 1745.5372314453125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 711.876708984375,
            "posy": 0.0,
            "posz": 1744.0765380859375,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 1756.6729736328125,
            "posy": 0.0,
            "posz": -723.689453125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 1762.678955078125,
            "posy": 0.0,
            "posz": 729.6946411132812,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -1798.712890625,
            "posy": 0.0,
            "posz": 747.7120971679688,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -1786.701416015625,
            "posy": 0.0,
            "posz": -729.6951293945312,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF 7E 7D",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1185.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "B300Snd",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -717.3648071289062,
            "posy": 0.0,
            "posz": 1747.6514892578125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 713.99072265625,
            "posy": 0.0,
            "posz": 1746.1907958984375,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 1758.787109375,
            "posy": 0.0,
            "posz": -721.575439453125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": 1764.7930908203125,
            "posy": 0.0,
            "posz": 731.8086547851562,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -1796.5987548828125,
            "posy": 0.0,
            "posz": 749.8261108398438,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF EF F1",
            "unk2": "04 FF FF FF",
            "posx": -1784.5872802734375,
            "posy": 0.0,
            "posz": -727.5811157226562,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Tubo",
            "extra_info": {
                "flagid": 254,
                "areaflag": "temp flag: 0xE 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF 01",
            "unk2": "FF FF FF FF",
            "posx": -11.152819633483887,
            "posy": 0.0,
            "posz": 950.0112915039062,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "TgSBG",
            "type": "STAG",
            "roomid": 0,
            "layerid": 2,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "B300Snd",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B300"
        },
        {
            "unk1": "FF FF 7E 7D",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -1185.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "HeartCo",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "B300"
        }
    ]
});