/* eslint-disable */export default Object.freeze({
    "stageid": "B400",
    "stagename": "Sealed Grounds: Last Boss",
    "maxx": 300.0,
    "minx": 0,
    "maxz": 0,
    "minz": -500.0,
    "usedLayers": [
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF C0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "BLasBos",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "unk1": "61 EA D3 F3",
            "unk2": "FF 1F FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 6669,
            "unk3": "FC 01",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 692,
                "untrigstoryfid": 783,
                "trigstoryf": "(not implemented yet -- 7771)",
                "untrigstoryf": "",
                "trigscenefid": 255,
                "untrigscenefid": 255,
                "trigscenef": "no flag",
                "untrigscenef": "no flag",
                "eventSrc": "006-6KenseiNormal.c#L830"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "LbTnder",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "unk1": "FF FF FF 03",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "TgSBG",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "unk1": "FF C0 FF 01",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -100.0,
            "posz": 0.0,
            "sizex": 25500.0,
            "sizey": 3000.0,
            "sizez": 25500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 04",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        }
    ]
});