/* eslint-disable */export default Object.freeze({
    "stageid": "B400",
    "stagename": "Sealed Grounds: Last Boss",
    "maxx": 300.0,
    "minx": 0,
    "maxz": 0,
    "minz": -500.0,
    "usedLayers": [
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -64,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "BLasBos",
            "angle": 0,
            "bin": "1111 1111 1111 1111 1111 1111 1100 0000",
            "extraInfo": {
                "first_4_bytes": "FF FF FF C0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "byte1": 97,
            "tosky_scen_link": -22,
            "scen_link": -45,
            "byte4": -13,
            "unk1": "FF 1F FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 6669,
            "unk3": "FC 01",
            "name": "NpcTke",
            "angle": -1,
            "bin": "0110 0001 1110 1010 1101 0011 1111 0011",
            "extraInfo": {
                "first_4_bytes": "61 EA D3 F3",
                "trigstoryfid": 692,
                "untrigstoryfid": 783,
                "trigstoryf": "(not implemented yet -- 7771)",
                "untrigstoryf": "",
                "trigscenefid": -1,
                "untrigscenefid": -1,
                "trigscenef": "no flag set",
                "untrigscenef": "no flag set",
                "eventSrc": "006-6KenseiNormal.c#L830"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "LbTnder",
            "angle": 0,
            "bin": "1111 1111 1111 1111 1111 1111 1111 1111",
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 3,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "TgSBG",
            "angle": 0,
            "bin": "1111 1111 1111 1111 1111 1111 0000 0011",
            "extraInfo": {
                "first_4_bytes": "FF FF FF 03"
            },
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -64,
            "scen_link": -1,
            "byte4": 1,
            "unk1": "FF DF FF FF",
            "posx": 0.0,
            "posy": -100.0,
            "posz": 0.0,
            "sizex": 25500.0,
            "sizey": 3000.0,
            "sizez": 25500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 65535,
            "unk3": "FC 04",
            "name": "Cam2Tag",
            "angle": 0,
            "bin": "1111 1111 1100 0000 1111 1111 0000 0001",
            "extraInfo": {
                "first_4_bytes": "FF C0 FF 01"
            },
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "B400"
        }
    ]
});