/* eslint-disable */export default Object.freeze({
    "stageid": "D003_7",
    "stagename": "Skyloft: Sky Keep R07 (Entrance)",
    "maxx": 3500.0,
    "minx": -5013.849609375,
    "maxz": 3500.0,
    "minz": -3679.11962890625,
    "usedLayers": [
        0,
        4,
        5
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FC 63 30 D7",
            "unk2": "FF FF FF FF",
            "posx": 2600.0,
            "posy": 0.0,
            "posz": -410.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "CtrlPnl",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -5013.849609375,
            "posy": 0.0,
            "posz": -187.12501525878906,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "D3Dummy",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF F0 6F 16",
            "unk2": "FF FF FF FF",
            "posx": 1967.2607421875,
            "posy": 0.0,
            "posz": -0.14831200242042542,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "FShutte",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 270.0,
            "posy": 150.0,
            "posz": -250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 270.0,
            "posy": 150.0,
            "posz": 250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -270.0,
            "posy": 150.0,
            "posz": 250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -270.0,
            "posy": 150.0,
            "posz": -250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF 1F FF FF",
            "posx": -2239.00732421875,
            "posy": 1785.6827392578125,
            "posz": -3679.11962890625,
            "event_flag": 23,
            "transition_type": 26,
            "angle": 65535,
            "talk_behaviour": 12501,
            "unk3": "FC 0B",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 26,
                "untrigscenefid": 23,
                "trigscenef": "scene flag: 0x2 04",
                "untrigscenef": "scene flag: 0x3 80"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF F8 38 40",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 3150.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "ShtCS",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF F8 34 40",
            "unk2": "FF 7F FF FF",
            "posx": 3150.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "ShtCS",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 6.407299995422363,
            "posy": 37.20000076293945,
            "posz": -1.6881309747695923,
            "event_flag": 255,
            "transition_type": 21,
            "angle": 0,
            "talk_behaviour": 32818,
            "unk3": "FC 03",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 21,
                "trigscenef": "scene flag: 0x3 20",
                "itemid": 50,
                "chestid": 64,
                "item": "Dungeon Map (and fi text)"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF 02 02 4E",
            "unk2": "FF 5F FF FF",
            "posx": -621.9866943359375,
            "posy": 0.0,
            "posz": 2150.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 16384,
            "talk_behaviour": 65535,
            "unk3": "FC 06",
            "name": "saveObj",
            "extra_info": {
                "flagid": 78,
                "tosky_scen_link": 2,
                "areaflag": "scene flag: 0x8 40"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 3500.0,
            "posy": -40.0,
            "posz": 0.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "TgD3Chg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -40.0,
            "posz": 3500.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "TgD3Chg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF 5F FF FF",
            "posx": 3300.0,
            "posy": -100.0,
            "posz": 0.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 250,
            "transition_type": 181,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0E",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": 18.78565788269043,
            "posy": 0.0,
            "posz": -2340.39306640625,
            "sizex": 8000.0,
            "sizey": 10000.0,
            "sizez": 2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": -2272.531005859375,
            "posy": 0.0,
            "posz": 214.2928466796875,
            "sizex": 2000.0,
            "sizey": 10000.0,
            "sizez": 8000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": 3297.738037109375,
            "posy": 0.0,
            "posz": 2742.642578125,
            "sizex": 4000.0,
            "sizey": 10000.0,
            "sizez": 4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": -2759.7646484375,
            "posy": 0.0,
            "posz": 3282.550048828125,
            "sizex": 4000.0,
            "sizey": 10000.0,
            "sizez": 4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": 2784.167236328125,
            "posy": 0.0,
            "posz": 3269.3818359375,
            "sizex": 4000.0,
            "sizey": 10000.0,
            "sizez": 4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "F0 45 45 80",
            "unk2": "FF FF FF FF",
            "posx": -11.028653144836426,
            "posy": -100.0,
            "posz": 21.456859588623047,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "SwTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -1000.0,
            "posz": 0.0,
            "sizex": 6500.0,
            "sizey": 6000.0,
            "sizez": 6500.0,
            "event_flag": 250,
            "transition_type": 189,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 15",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF 15 16 03",
            "unk2": "FF FF FF FF",
            "posx": 47.40853500366211,
            "posy": -100.0,
            "posz": -8.293807029724121,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 4,
            "stageid": "D003_7"
        },
        {
            "unk1": "FF F8 9F 00",
            "unk2": "FF FF FF FF",
            "posx": -10.644770622253418,
            "posy": -100.0,
            "posz": 2944.131591796875,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "EvfTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 5,
            "stageid": "D003_7"
        }
    ]
});