/* eslint-disable */export default Object.freeze({
    "stageid": "D003_8",
    "stagename": "Skyloft: Sky Keep R08 Tri Get",
    "maxx": 273.2935791015625,
    "minx": -1940.9512939453125,
    "maxz": 1035.5716552734375,
    "minz": -436.1156311035156,
    "usedLayers": [
        0,
        1,
        2,
        3,
        5,
        6
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 273.2935791015625,
            "posy": 142.77684020996094,
            "posz": -247.2414093017578,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 271.520263671875,
            "posy": 142.49151611328125,
            "posz": 252.8332977294922,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -271.114013671875,
            "posy": 141.9358367919922,
            "posz": -249.0147247314453,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -269.3406982421875,
            "posy": 141.88168334960938,
            "posz": 251.0599822998047,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF 00 1D 1D",
            "unk2": "FF 7F FF FF",
            "posx": 0.0,
            "posy": -100.0,
            "posz": 0.0,
            "event_flag": 255,
            "transition_type": 242,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "WarpObj",
            "extra_info": {
                "scen_link": 0,
                "trigscenefid": 29,
                "untrigscenefid": 29,
                "trigscenef": "scene flag: 0x2 20",
                "untrigscenef": "scene flag: 0x2 20"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "UdCloud",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF FF FF 03",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Vrbox",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "D4 2F FF 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "EvfTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF 0C FA 61",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 180.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Item",
            "extra_info": {
                "flagid": 62,
                "itemid": 97,
                "areaflag": "scene flag: 0x6 40",
                "item": "Triforce of Wisdom"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF 0C F6 60",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 180.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Item",
            "extra_info": {
                "flagid": 61,
                "itemid": 96,
                "areaflag": "scene flag: 0x6 20",
                "item": "Triforce of Power"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF 0D 02 5F",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 180.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Item",
            "extra_info": {
                "flagid": 64,
                "itemid": 95,
                "areaflag": "scene flag: 0x9 01",
                "item": "Triforce of Courage"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "D003_8"
        },
        {
            "unk1": "50 CA 17 11",
            "unk2": "FF 1F FF FF",
            "posx": -1940.9512939453125,
            "posy": 1188.02392578125,
            "posz": -436.1156311035156,
            "event_flag": 255,
            "transition_type": 60,
            "angle": 65535,
            "talk_behaviour": 12502,
            "unk3": "FC 08",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 645,
                "untrigstoryfid": 646,
                "trigstoryf": "Set when beating Sky Keep",
                "untrigstoryf": "",
                "trigscenefid": 60,
                "untrigscenefid": 255,
                "trigscenef": "scene flag: 0x6 10",
                "untrigscenef": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5,
            "stageid": "D003_8"
        },
        {
            "unk1": "FF 03 1D 1D",
            "unk2": "FF 7F FF FF",
            "posx": 6.560770034790039,
            "posy": -500.0,
            "posz": 1035.5716552734375,
            "event_flag": 255,
            "transition_type": 242,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "WarpObj",
            "extra_info": {
                "scen_link": 3,
                "trigscenefid": 29,
                "untrigscenefid": 29,
                "trigscenef": "scene flag: 0x2 20",
                "untrigscenef": "scene flag: 0x2 20"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6,
            "stageid": "D003_8"
        }
    ]
});