/* eslint-disable */export default Object.freeze({
    "stageid": "D301_1",
    "stagename": "Lanayru Desert: Sandship (B)",
    "maxx": 4140.0,
    "minx": -6101.58447265625,
    "maxz": 2122.48828125,
    "minz": -1550.0,
    "usedLayers": [
        "l0"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -65.65967559814453,
            "posy": -700.0,
            "posz": -716.5277709960938,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -65.65967559814453,
            "posy": -700.0,
            "posz": -849.1857299804688,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 1752.5355224609375,
            "posy": -700.0,
            "posz": -146.8785400390625,
            "event_flag": 64,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 2251.953857421875,
            "posy": -700.0,
            "posz": 63.813560485839844,
            "event_flag": 64,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 1151.6728515625,
            "posy": -700.0,
            "posz": 40.40333557128906,
            "event_flag": 64,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -4225.0,
            "posy": -30.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -850.0,
            "posy": -60.0,
            "posz": 740.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -570.0,
            "posy": -60.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -850.0,
            "posy": -60.0,
            "posz": -790.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1050.0,
            "posy": -60.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 3050.0,
            "posy": -60.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 4140.0,
            "posy": -60.0,
            "posz": 350.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 4140.0,
            "posy": -60.0,
            "posz": 1550.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1840.0,
            "posy": -980.0,
            "posz": 1825.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -240.0,
            "posy": -980.0,
            "posz": 1825.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2170.0,
            "posy": -800.0,
            "posz": 1330.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2170.0,
            "posy": -800.0,
            "posz": -1330.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "ElLight",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": -677.4479370117188,
            "posy": -1600.0,
            "posz": 2100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 78.77021789550781,
            "posy": -1600.0,
            "posz": 2100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 4,
            "unk1": "FF FF FF FF",
            "posx": -1650.0,
            "posy": -700.0,
            "posz": -1550.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 4,
            "unk1": "FF FF FF FF",
            "posx": -700.0,
            "posy": -700.0,
            "posz": 1550.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -25,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -321.8974609375,
            "posy": -1610.0,
            "posz": -372.1446838378906,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -21,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -237.0614013671875,
            "posy": -1610.0,
            "posz": 459.247802734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -21,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 88.921630859375,
            "posy": -1610.0,
            "posz": -816.6524658203125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -21,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 305.8888244628906,
            "posy": -1610.0,
            "posz": 747.6900634765625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -21,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 814.0032958984375,
            "posy": -1610.0,
            "posz": -560.0134887695312,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -21,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 837.035888671875,
            "posy": -1610.0,
            "posz": 459.247802734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "BKrA",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 6,
            "unk1": "FF 1F FF FF",
            "posx": -1147.705078125,
            "posy": -1173.923095703125,
            "posz": 2122.48828125,
            "event_flag": 79,
            "transition_type": -1,
            "unk2": "FF 00",
            "talk_behaviour": -25427,
            "unk3": "FC 1D",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 2,
            "unk1": "FF 1F FF FF",
            "posx": -6101.58447265625,
            "posy": 98.60646057128906,
            "posz": 111.8030776977539,
            "event_flag": 48,
            "transition_type": -1,
            "unk2": "FF 03",
            "talk_behaviour": -25423,
            "unk3": "FC 1E",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": -800.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 38",
            "name": "STSink",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": -2150.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 39",
            "name": "STWater",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 0,
            "byte4": 5,
            "unk1": "FF 5F FF FF",
            "posx": -3015.0,
            "posy": 0.0,
            "posz": 80.0,
            "event_flag": -1,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -16,
            "unk3": "FC 0E",
            "name": "Door",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 0,
            "byte4": 5,
            "unk1": "FF 5F FF FF",
            "posx": -3015.0,
            "posy": 0.0,
            "posz": -80.0,
            "event_flag": -1,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": -16,
            "unk3": "FC 0F",
            "name": "Door",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -16,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 2850.0,
            "posy": -2550.0,
            "posz": 1850.0,
            "sizex": 8.0,
            "sizey": 5.0,
            "sizez": 5.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "ClrWall",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        }
    ]
});