/* eslint-disable */export default Object.freeze({
    "stageid": "F006r",
    "stagename": "Skyloft: Repairman Kukiel\u2019s House",
    "maxx": 900.0,
    "minx": -549.5950927734375,
    "maxz": 24.437759399414062,
    "minz": -1730.0,
    "usedLayers": [
        0,
        1,
        2
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF E0 24",
            "unk2": "FF FF FF FF",
            "posx": 456.322998046875,
            "posy": 51.0,
            "posz": -1152.107666015625,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 21663,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "DNight",
            "extra_info": {
                "sleep_storyf": 36
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "2F 02 FF FF",
            "unk2": "FF FF FF FF",
            "posx": 900.0,
            "posy": 0.0,
            "posz": -370.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "chest",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "00 00 00 00",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 10,
            "transition_type": 2,
            "angle": 60075,
            "talk_behaviour": 65535,
            "unk3": "FC 14",
            "name": "Door",
            "extra_info": {
                "flagid": 10,
                "scen_link": 0,
                "areaflag": "scene flag: 0x0 04"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -549.5950927734375,
            "posy": 0.0,
            "posz": -1024.158203125,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "GkMgTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "FF FF 04 02",
            "unk2": "FF FF FF FF",
            "posx": -95.0,
            "posy": 40.0,
            "posz": -1730.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF 5F FF FF",
            "posx": 43.384395599365234,
            "posy": -24.73381805419922,
            "posz": 24.437759399414062,
            "sizex": 671.0,
            "sizey": 100.0,
            "sizez": 384.0,
            "event_flag": 250,
            "transition_type": 202,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 19",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 23.65290641784668,
            "posy": -60.132781982421875,
            "posz": -45.78361892700195,
            "sizex": 200.0,
            "sizey": 100.0,
            "sizez": 130.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 27306,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "AttTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F006r"
        },
        {
            "unk1": "FF E4 C3 F0",
            "unk2": "FF 5F FF FF",
            "posx": 83.02333068847656,
            "posy": 0.0,
            "posz": -596.7702026367188,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 59165,
            "talk_behaviour": 11808,
            "unk3": "FC 1B",
            "name": "NpcSoMo",
            "extra_info": {
                "trigstoryfid": 304,
                "untrigstoryfid": 2047,
                "trigstoryf": "Start Batreaux quest (enables Gratitude crystals)",
                "untrigstoryf": "-",
                "eventSrc": "118-Town3.c#L232"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F006r"
        },
        {
            "unk1": "02 25 27 11",
            "unk2": "FF 5F FF FF",
            "posx": 422.3486022949219,
            "posy": 0.0,
            "posz": -237.85841369628906,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 10012,
            "talk_behaviour": 11812,
            "unk3": "FC 1C",
            "name": "NpcSoG",
            "extra_info": {
                "trigstoryfid": 329,
                "untrigstoryfid": 17,
                "trigstoryf": "Sleeping after starting Batreaux quest",
                "untrigstoryf": "Beat Sky Keep (Goddess Statue has fallen on Skyloft) (Skyloft layers 8&9)",
                "eventSrc": "118-Town3.c#L575"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F006r"
        },
        {
            "unk1": "04 9F FF F0",
            "unk2": "FF 5F FF FF",
            "posx": 129.59251403808594,
            "posy": 0.0,
            "posz": -606.0840454101562,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 59165,
            "talk_behaviour": 12209,
            "unk3": "FC 1D",
            "name": "NpcSoMo",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 36,
                "trigstoryf": "-",
                "untrigstoryf": "Hero's Tunic (Skyloft layers 4&5 / Sky layer 2 / Knight Academy layers 3&4 / Sealed Grounds layer 1 / Behind The Temple layer 1 / Goddess Statue layers 2&3)",
                "eventSrc": "122-Town4.c#L194"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F006r"
        },
        {
            "unk1": "FF E4 C3 F0",
            "unk2": "FF 5F FF FF",
            "posx": -307.54791259765625,
            "posy": 0.0,
            "posz": -1450.197998046875,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 37866,
            "talk_behaviour": 11808,
            "unk3": "FC 1B",
            "name": "NpcSoMo",
            "extra_info": {
                "trigstoryfid": 304,
                "untrigstoryfid": 2047,
                "trigstoryf": "Start Batreaux quest (enables Gratitude crystals)",
                "untrigstoryf": "-",
                "eventSrc": "118-Town3.c#L232"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F006r"
        },
        {
            "unk1": "FF E5 27 F0",
            "unk2": "FF 5F FF FF",
            "posx": 355.0,
            "posy": 57.18063735961914,
            "posz": -1300.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 57344,
            "talk_behaviour": 12211,
            "unk3": "FC 1C",
            "name": "NpcSoG",
            "extra_info": {
                "trigstoryfid": 329,
                "untrigstoryfid": 2047,
                "trigstoryf": "Sleeping after starting Batreaux quest",
                "untrigstoryf": "-",
                "eventSrc": "122-Town4.c#L237"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F006r"
        },
        {
            "unk1": "2D 1F FF FF",
            "unk2": "FF 5F FF FF",
            "posx": 225.05001831054688,
            "posy": 0.0,
            "posz": -1104.7816162109375,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 25304,
            "talk_behaviour": 12212,
            "unk3": "FC 1D",
            "name": "NpcSoFa",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 360,
                "trigstoryf": "-",
                "untrigstoryf": "Batreaux turns human",
                "eventSrc": "122-Town4.c#L248"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F006r"
        },
        {
            "unk1": "26 1F FF F0",
            "unk2": "FF 5F FF FF",
            "posx": -279.60638427734375,
            "posy": 0.0,
            "posz": -1445.541015625,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 37866,
            "talk_behaviour": 12213,
            "unk3": "FC 1E",
            "name": "NpcSoMo",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 304,
                "trigstoryf": "-",
                "untrigstoryf": "Start Batreaux quest (enables Gratitude crystals)",
                "eventSrc": "122-Town4.c#L279"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F006r"
        },
        {
            "unk1": "25 FF FF F0",
            "unk2": "FF 5F FF FF",
            "posx": 355.0,
            "posy": 57.18063735961914,
            "posz": -1300.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 57344,
            "talk_behaviour": 12211,
            "unk3": "FC 1F",
            "name": "NpcSoG",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 303,
                "trigstoryf": "-",
                "untrigstoryf": "Wryna asks Link to find Kukiel (allows Kukiel to scream to unlock Batreaux's door)",
                "eventSrc": "122-Town4.c#L237"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F006r"
        }
    ]
});