/* eslint-disable */export default Object.freeze({
    "stageid": "F008r",
    "stagename": "Skyloft: Inside the Statue of the Goddess",
    "maxx": 455.0,
    "minx": -2806.257568359375,
    "maxz": 496.839111328125,
    "minz": -1458.0,
    "usedLayers": [
        0,
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -455.0,
            "posy": 210.0,
            "posz": -1458.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 455.0,
            "posy": 210.0,
            "posz": -1458.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 2,
            "byte4": 25,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 93.60000610351562,
            "posz": -1310.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "SndStn",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -435.0,
            "posy": 123.0,
            "posz": -206.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 435.0,
            "posy": 123.0,
            "posz": -206.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 42.820003509521484,
            "posz": 75.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "SwrdSt",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -32,
            "scen_link": -65,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -347.62298583984375,
            "posy": 2.0,
            "posz": -811.4651489257812,
            "event_flag": 95,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 10761,
            "unk3": "FC 06",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -32,
            "scen_link": -61,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -465.654296875,
            "posy": 2.0,
            "posz": -772.1213989257812,
            "event_flag": 96,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 10762,
            "unk3": "FC 07",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 4,
            "tosky_scen_link": -128,
            "scen_link": -117,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 302.2035217285156,
            "posy": 241.53829956054688,
            "posz": -507.0137939453125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "EC CD",
            "talk_behaviour": 10753,
            "unk3": "FC 0A",
            "name": "NpcKen",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 4,
            "tosky_scen_link": -128,
            "scen_link": -101,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 138.28195190429688,
            "posy": 11.785662651062012,
            "posz": 496.839111328125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "8D 83",
            "talk_behaviour": 10303,
            "unk3": "FC 0B",
            "name": "NpcDsk",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -2806.257568359375,
            "posy": 144.12060546875,
            "posz": -128.14373779296875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -335,
            "unk3": "FC 0C",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -2599.9169921875,
            "posy": 144.12060546875,
            "posz": 157.24252319335938,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -501,
            "unk3": "FC 0D",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 1
        }
    ]
});