/* eslint-disable */export default Object.freeze({
    "stageid": "F010r",
    "stagename": "Skyloft: Isle of Songs Tower",
    "maxx": 4100.0,
    "minx": -179.46446228027344,
    "maxz": 16028.5556640625,
    "minz": -500.0,
    "usedLayers": [
        0,
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF F1 32",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "SwSB",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF E1 1F 11",
            "unk2": "FF 1F FF FF",
            "posx": 3600.0,
            "posy": 0.0,
            "posz": 3000.0,
            "event_flag": 71,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 19971,
            "unk3": "FC 02",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 71,
                "untrigstoryfid": 2047,
                "trigstoryf": "Learn Farore's Courage (Faron Woods layer 3 / Deep Woods layer 3)",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 71,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0x9 80",
                "eventSrc": "199-Demo.c#L19"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF E1 23 11",
            "unk2": "FF 1F FF FF",
            "posx": 3850.0,
            "posy": 0.0,
            "posz": 3000.0,
            "event_flag": 72,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 19972,
            "unk3": "FC 03",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 72,
                "untrigstoryfid": 2047,
                "trigstoryf": "Learn Nayru's Wisdom",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 72,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0x8 01",
                "eventSrc": "199-Demo.c#L33"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF E1 27 11",
            "unk2": "FF 1F FF FF",
            "posx": 4100.0,
            "posy": 0.0,
            "posz": 3000.0,
            "event_flag": 73,
            "transition_type": 255,
            "angle": 65535,
            "talk_behaviour": 19973,
            "unk3": "FC 04",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 73,
                "untrigstoryfid": 2047,
                "trigstoryf": "Learn Din's Power",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 73,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0x8 02",
                "eventSrc": "199-Demo.c#L40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF FF 00 35",
            "unk2": "FF 5F FF FF",
            "posx": -179.46446228027344,
            "posy": 395.57000732421875,
            "posz": 4651.8583984375,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65535,
            "unk3": "FC 01",
            "name": "saveObj",
            "extra_info": {
                "flagid": 53,
                "tosky_scen_link": 255,
                "areaflag": "scene flag: 0x7 20"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 5000.0,
            "sizex": 600.0,
            "sizey": 600.0,
            "sizez": 200.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 05",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF FF 01 01",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 4600.0,
            "sizex": 800.0,
            "sizey": 600.0,
            "sizez": 600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 06",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF F2 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0004189999890513718,
            "posy": 56.59185791015625,
            "posz": 16028.5556640625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 07",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF F1 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0004189999890513718,
            "posy": 56.59185791015625,
            "posz": 16028.5556640625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 08",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF F0 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0004189999890513718,
            "posy": 56.59185791015625,
            "posz": 16028.5556640625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 09",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F010r"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "DemoPds",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F010r"
        }
    ]
});