/* eslint-disable */export default Object.freeze({
    "stageid": "F012r",
    "stagename": "Skyloft: Demon Guy Batreaux\u2019s House",
    "maxx": 485.9203796386719,
    "minx": -490.7880859375,
    "maxz": 1350.0,
    "minz": -400.0,
    "usedLayers": [
        "l0",
        "l1"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": 41,
            "tosky_scen_link": 63,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF 5F FF FF",
            "posx": -490.7880859375,
            "posy": 40.0,
            "posz": 264.6295166015625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "41 6C",
            "talk_behaviour": 11811,
            "unk3": "FC 01",
            "name": "NpcSoG",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 550.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "DecoB",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": 410.0,
            "posy": 310.0,
            "posz": 80.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E7 1D",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Paint",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -410.0,
            "posy": 310.0,
            "posz": 80.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "18 E3",
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Paint",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 0,
            "byte4": 6,
            "unk1": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 1350.0,
            "event_flag": 78,
            "transition_type": 1,
            "unk2": "00 00",
            "talk_behaviour": -16,
            "unk3": "FC 00",
            "name": "Door",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -150.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -404,
            "unk3": "FC 02",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -50.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -403,
            "unk3": "FC 03",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 50.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -402,
            "unk3": "FC 04",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 150.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -401,
            "unk3": "FC 05",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 264.0943908691406,
            "posy": 0.0,
            "posz": -393.6614990234375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -418,
            "unk3": "FC 06",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -11,
            "tosky_scen_link": 63,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 485.9203796386719,
            "posy": 0.0,
            "posz": 588.1489868164062,
            "event_flag": -1,
            "transition_type": -64,
            "unk2": "C0 00",
            "talk_behaviour": -30104,
            "unk3": "FC 0A",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -6.0,
            "posy": 60.0,
            "posz": 175.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 12130,
            "unk3": "FC 20",
            "name": "NpcAkum",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -106,
            "tosky_scen_link": 31,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -6.0,
            "posy": 60.0,
            "posz": 175.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 12130,
            "unk3": "FC 21",
            "name": "NpcAkuH",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF 1F FF FF",
            "posx": -130.6027069091797,
            "posy": 60.0,
            "posz": 246.20155334472656,
            "event_flag": 84,
            "transition_type": 83,
            "unk2": "FF 00",
            "talk_behaviour": 12102,
            "unk3": "FC 22",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 13,
            "tosky_scen_link": 11,
            "scen_link": 123,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -373.2391052246094,
            "posy": 36.64811706542969,
            "posz": 784.4090576171875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "FF 01",
            "talk_behaviour": 10756,
            "unk3": "FC 23",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        }
    ]
});