/* eslint-disable */export default Object.freeze({
    "stageid": "F012r",
    "stagename": "Skyloft: Demon Guy Batreaux\u2019s House",
    "maxx": 617.2200317382812,
    "minx": -617.2200317382812,
    "maxz": 1350.0,
    "minz": -400.0,
    "usedLayers": [
        0,
        1
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "29 3F FF F0",
            "unk2": "FF 5F FF FF",
            "posx": -490.7880859375,
            "posy": 40.0,
            "posz": 264.6295166015625,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 16748,
            "talk_behaviour": 11811,
            "unk3": "FC 01",
            "name": "NpcSoG",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 329,
                "trigstoryf": "-",
                "untrigstoryf": "Sleeping after starting Batreaux quest",
                "eventSrc": "118-Town3.c#L517"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 550.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "DecoB",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF FC",
            "unk2": "FF FF FF FF",
            "posx": 410.0,
            "posy": 310.0,
            "posz": 80.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 59165,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Paint",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF FC",
            "unk2": "FF FF FF FF",
            "posx": -410.0,
            "posy": 310.0,
            "posz": 80.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 6371,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Paint",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "00 00 00 06",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 1350.0,
            "event_flag": 78,
            "transition_type": 1,
            "angle": 0,
            "talk_behaviour": 65520,
            "unk3": "FC 00",
            "name": "Door",
            "extra_info": {
                "flagid": 78,
                "scen_link": 0,
                "areaflag": "scene flag: 0x8 40"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -150.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65132,
            "unk3": "FC 02",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 108,
                "chestid": 127,
                "item": "Medium Wallet"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -50.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65133,
            "unk3": "FC 03",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 109,
                "chestid": 127,
                "item": "Big Wallet"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 50.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65134,
            "unk3": "FC 04",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 110,
                "chestid": 127,
                "item": "Giant Wallet"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 150.0,
            "posy": 0.0,
            "posz": -400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65135,
            "unk3": "FC 05",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 111,
                "chestid": 127,
                "item": "Tycoon Wallet"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 264.0943908691406,
            "posy": 0.0,
            "posz": -393.6614990234375,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65118,
            "unk3": "FC 06",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 94,
                "chestid": 127,
                "item": "Heart piece"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "F5 3F FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 485.9203796386719,
            "posy": 0.0,
            "posz": 588.1489868164062,
            "event_flag": 255,
            "transition_type": 192,
            "angle": 49152,
            "talk_behaviour": 35432,
            "unk3": "FC 0A",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 83,
                "spawnscenef": "scene flag: 0xB 08",
                "trigscenefid": 192,
                "trigscenef": "temp flag: 0x9 01",
                "itemid": 104,
                "chestid": 69,
                "item": "Cursed Medal"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 0.2709279954433441,
            "posy": -10.73340129852295,
            "posz": 1269.7603759765625,
            "sizex": 200.0,
            "sizey": 100.0,
            "sizez": 130.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "AttTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -589.1100463867188,
            "posy": 350.0,
            "posz": 913.760009765625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -603.1600341796875,
            "posy": 360.0,
            "posz": 879.8400268554688,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -617.2200317382812,
            "posy": 350.0,
            "posz": 845.9100341796875,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -617.2200317382812,
            "posy": 350.0,
            "posz": 414.09002685546875,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -603.1600341796875,
            "posy": 360.0,
            "posz": 380.1600036621094,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -589.1100463867188,
            "posy": 350.0,
            "posz": 346.2400207519531,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -276.7200012207031,
            "posy": 240.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -240.0,
            "posy": 250.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -203.28001403808594,
            "posy": 240.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 203.28001403808594,
            "posy": 240.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 240.0,
            "posy": 250.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 276.7200012207031,
            "posy": 240.0,
            "posz": 49.93000030517578,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 589.1100463867188,
            "posy": 350.0,
            "posz": 346.2400207519531,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 603.1600341796875,
            "posy": 360.0,
            "posz": 380.1600036621094,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 617.2200317382812,
            "posy": 350.0,
            "posz": 414.09002685546875,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 617.2200317382812,
            "posy": 350.0,
            "posz": 845.9100341796875,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 603.1600341796875,
            "posy": 360.0,
            "posz": 879.8400268554688,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 589.1100463867188,
            "posy": 350.0,
            "posz": 913.760009765625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": 249.85000610351562,
            "posy": 220.0,
            "posz": 1233.1900634765625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF 03 02",
            "unk2": "FF FF FF FF",
            "posx": -249.85000610351562,
            "posy": 220.0,
            "posz": 1233.1900634765625,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "EffGnT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF 5F FF FF",
            "posx": -6.0,
            "posy": 60.0,
            "posz": 175.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 12130,
            "unk3": "FC 20",
            "name": "NpcAkum",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "121-AkumaKun.c#L96"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F012r"
        },
        {
            "unk1": "96 1F FF FF",
            "unk2": "FF 5F FF FF",
            "posx": -6.0,
            "posy": 60.0,
            "posz": 175.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 12130,
            "unk3": "FC 21",
            "name": "NpcAkuH",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 1200,
                "trigstoryf": "-",
                "untrigstoryf": "",
                "eventSrc": "121-AkumaKun.c#L96"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F012r"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 1F FF FF",
            "posx": -130.6027069091797,
            "posy": 60.0,
            "posz": 246.20155334472656,
            "event_flag": 84,
            "transition_type": 83,
            "angle": 65280,
            "talk_behaviour": 12102,
            "unk3": "FC 22",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 83,
                "untrigscenefid": 84,
                "trigscenef": "scene flag: 0xB 08",
                "untrigscenef": "scene flag: 0xB 10",
                "eventSrc": "121-AkumaKun.c#L1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F012r"
        },
        {
            "unk1": "0D 0B 7B F2",
            "unk2": "FF 1F FF FF",
            "posx": -373.2391052246094,
            "posy": 36.64811706542969,
            "posz": 784.4090576171875,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 65281,
            "talk_behaviour": 10756,
            "unk3": "FC 23",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 734,
                "untrigstoryfid": 104,
                "trigstoryf": "Sets when talking to Batreaux after getting Crystals (allows Crystal Dowsing?)",
                "untrigstoryf": "Crystal Dowsing",
                "trigscenefid": 255,
                "untrigscenefid": 255,
                "trigscenef": "no flag",
                "untrigscenef": "no flag",
                "eventSrc": "107-Kanban.c#L11"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F012r"
        }
    ]
});