/* eslint-disable */export default Object.freeze({
    "stageid": "F102_2",
    "stagename": "Faron Woods: Faron's Lair",
    "maxx": 10200.0,
    "minx": -4950.0,
    "maxz": 15400.0,
    "minz": -11125.4599609375,
    "usedLayers": [
        0,
        1,
        3,
        4
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -61,
            "byte4": 15,
            "unk1": "FF FF FF FF",
            "posx": 6131.0,
            "posy": 55.0,
            "posz": -2746.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "WtrJar",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF C3 0F"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 7900.0,
            "posy": -600.0,
            "posz": -1050.0,
            "event_flag": -1,
            "transition_type": 1,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "NpcSuiS",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 7900.0,
            "posy": -400.0,
            "posz": -1350.0,
            "event_flag": -1,
            "transition_type": 1,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "NpcSuiS",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8500.0,
            "posy": -700.0,
            "posz": -1350.0,
            "event_flag": -1,
            "transition_type": 1,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "NpcSuiS",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8200.0,
            "posy": -300.0,
            "posz": -850.0,
            "event_flag": -1,
            "transition_type": 1,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "NpcSuiS",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8200.0,
            "posy": -300.0,
            "posz": -1550.0,
            "event_flag": -1,
            "transition_type": 1,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "NpcSuiS",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 4470.0,
            "posy": -1250.0,
            "posz": -1040.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20364,
            "unk3": "FC 07",
            "name": "NpcSuiN",
            "angle": 7207,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 5730.0,
            "posy": -1950.0,
            "posz": -5080.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20365,
            "unk3": "FC 08",
            "name": "NpcSuiN",
            "angle": 22229,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -2000.0,
            "posz": -500.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "Bubble",
            "angle": 7175,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 4300.0,
            "posy": -2001.950927734375,
            "posz": -4500.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Bubble",
            "angle": 11544,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 8000.0,
            "posy": -2004.4088134765625,
            "posz": -4800.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "Bubble",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 6760.0,
            "posy": -25.0,
            "posz": -5000.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "LtsFlwr",
            "angle": 21781,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 7450.0,
            "posy": -25.0,
            "posz": -4430.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "LtsFlwr",
            "angle": 22165,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 8450.0,
            "posy": -25.0,
            "posz": -4340.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "LtsFlwr",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 9080.0,
            "posy": -25.0,
            "posz": -3250.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "LtsFlwr",
            "angle": -21974,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 8190.0,
            "posy": -25.0,
            "posz": -5340.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "LtsFlwr",
            "angle": -21590,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 2830.0,
            "posy": -25.0,
            "posz": -3350.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "LtsFlwr",
            "angle": 21781,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 3800.0,
            "posy": -25.0,
            "posz": -2400.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "LtsFlwr",
            "angle": 22165,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 8450.0,
            "posy": -25.0,
            "posz": -1860.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "LtsFlwr",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 8120.0,
            "posy": -25.0,
            "posz": -220.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 20",
            "name": "LtsFlwr",
            "angle": -21974,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 4260.0,
            "posy": -25.0,
            "posz": -3690.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "LtsFlwr",
            "angle": -21590,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "06 FF FF FF",
            "posx": 7430.0,
            "posy": -25.0,
            "posz": -5050.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "LtsFlwr",
            "angle": -21974,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "26 FF FF FF",
            "posx": 8310.0,
            "posy": -25.0,
            "posz": -3350.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 23",
            "name": "LtsFlwr",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "06 FF FF FF",
            "posx": 9260.0,
            "posy": -25.0,
            "posz": -1420.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 24",
            "name": "LtsFlwr",
            "angle": -21974,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "26 FF FF FF",
            "posx": 3330.0,
            "posy": -25.0,
            "posz": -1810.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "LtsFlwr",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -16,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 2550.0,
            "posy": 151.20053100585938,
            "posz": -4650.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 26",
            "name": "Heartf",
            "angle": -21526,
            "extraInfo": {
                "first_4_bytes": "FF FF F0 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -16,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 2800.0,
            "posy": 151.4091796875,
            "posz": -4650.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 27",
            "name": "Heartf",
            "angle": 28956,
            "extraInfo": {
                "first_4_bytes": "FF FF F0 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -16,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 2150.0,
            "posy": 387.3030090332031,
            "posz": -3650.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 28",
            "name": "Heartf",
            "angle": -21910,
            "extraInfo": {
                "first_4_bytes": "FF FF F0 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 5118.6875,
            "posy": -1300.0,
            "posz": -646.5751953125,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 29",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 8160.0,
            "posy": -1970.0,
            "posz": -3940.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2A",
            "name": "AncJwls",
            "angle": -7400,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 9720.0,
            "posy": 633.7626953125,
            "posz": -4150.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2B",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "26 FF FF FF",
            "posx": 2400.0,
            "posy": 339.9452209472656,
            "posz": -1200.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2C",
            "name": "skull",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "04 FF FF FF",
            "posx": 4900.0,
            "posy": 640.4287719726562,
            "posz": 1000.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2D",
            "name": "skull",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "1E FF FF FF",
            "posx": 5400.0,
            "posy": 539.591796875,
            "posz": 700.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2E",
            "name": "skull",
            "angle": 22165,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "26 FF FF FF",
            "posx": 5900.0,
            "posy": 361.8805236816406,
            "posz": -6200.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2F",
            "name": "skull",
            "angle": -21526,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -25,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": 14,
            "transition_type": 56,
            "talk_behaviour": -1456,
            "unk3": "FC 5B",
            "name": "GodCube",
            "angle": 7623,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 E7"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -20,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": -15,
            "transition_type": -56,
            "talk_behaviour": 910,
            "unk3": "FC 5C",
            "name": "GodCube",
            "angle": -8483,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 EC"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": -2,
            "transition_type": -108,
            "talk_behaviour": -364,
            "unk3": "FC 5D",
            "name": "GodCube",
            "angle": 10445,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -29,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5E",
            "name": "GodCube",
            "angle": 21781,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 E3"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -28,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": -8,
            "transition_type": -28,
            "talk_behaviour": -910,
            "unk3": "FC 5F",
            "name": "GodCube",
            "angle": -22006,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 E4"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -12,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": -4,
            "transition_type": 114,
            "talk_behaviour": -910,
            "unk3": "FC 60",
            "name": "GodCube",
            "angle": 32,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F4"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -6,
            "unk1": "FF FF FF FF",
            "posx": -2243.2001953125,
            "posy": 1305.3555908203125,
            "posz": -11125.4599609375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 61",
            "name": "GodCube",
            "angle": 22229,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 FA"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -7,
            "unk1": "FF FF FF FF",
            "posx": -4350.0,
            "posy": 2452.102294921875,
            "posz": -6250.0,
            "event_flag": -4,
            "transition_type": 114,
            "talk_behaviour": -910,
            "unk3": "FC 62",
            "name": "GodCube",
            "angle": -17938,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F9"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -2,
            "unk1": "FF FF FF FF",
            "posx": -300.0,
            "posy": 600.0,
            "posz": 10000.0,
            "event_flag": -4,
            "transition_type": 114,
            "talk_behaviour": -1820,
            "unk3": "FC 63",
            "name": "GodCube",
            "angle": -21526,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 FE"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF 5F FF FF",
            "posx": 8500.0,
            "posy": -500.0,
            "posz": -1050.0,
            "event_flag": 2,
            "transition_type": 1,
            "talk_behaviour": 20381,
            "unk3": "FC 01",
            "name": "NpcSui",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 7550.0,
            "posy": 516.1200561523438,
            "posz": 950.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -22496,
            "unk3": "FC 09",
            "name": "TBox",
            "angle": -1084,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F3"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 10200.0,
            "posy": 565.1600341796875,
            "posz": -3100.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -21953,
            "unk3": "FC 0A",
            "name": "TBox",
            "angle": 16265,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F3"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": 34,
            "unk1": "FF 5F FF FF",
            "posx": 1110.0,
            "posy": -824.6444702148438,
            "posz": 15400.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -1,
            "unk3": "FC 57",
            "name": "saveObj",
            "angle": 224,
            "extraInfo": {
                "first_4_bytes": "FF FF 00 22",
                "flagid": 34,
                "areaflag": "scene flag: 0x5 04"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 1,
            "byte4": 32,
            "unk1": "FF 5F FF 07",
            "posx": 2660.0,
            "posy": 433.50311279296875,
            "posz": 8110.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -1,
            "unk3": "FC 58",
            "name": "saveObj",
            "angle": 22261,
            "extraInfo": {
                "first_4_bytes": "FF FF 01 20",
                "flagid": 32,
                "areaflag": "scene flag: 0x5 01"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 1,
            "byte4": 33,
            "unk1": "FF 5F FF 08",
            "posx": -4950.0,
            "posy": 249.05262756347656,
            "posz": -5700.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -1,
            "unk3": "FC 59",
            "name": "saveObj",
            "angle": -14543,
            "extraInfo": {
                "first_4_bytes": "FF FF 01 21",
                "flagid": 33,
                "areaflag": "scene flag: 0x5 02"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 1460.0,
            "posy": 900.0,
            "posz": 7460.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -32592,
            "unk3": "FC 5A",
            "name": "TBox",
            "angle": 21845,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F3"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 9131.0,
            "posy": -800.0,
            "posz": -2746.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 30",
            "name": "Light00",
            "angle": 192,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 8231.0,
            "posy": -800.0,
            "posz": -4846.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 31",
            "name": "Light00",
            "angle": 224,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 6131.0,
            "posy": -800.0,
            "posz": -5746.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 32",
            "name": "Light00",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 4031.0,
            "posy": -800.0,
            "posz": -4846.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 33",
            "name": "Light00",
            "angle": 32,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 3131.0,
            "posy": -800.0,
            "posz": -2746.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 34",
            "name": "Light00",
            "angle": 64,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 4031.0,
            "posy": -800.0,
            "posz": -646.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "Light00",
            "angle": 96,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 6131.0,
            "posy": -800.0,
            "posz": 254.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 36",
            "name": "Light00",
            "angle": 128,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 8031.0,
            "posy": -800.0,
            "posz": -846.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 37",
            "name": "Light00",
            "angle": 160,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 00"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8470.0,
            "posy": -2000.0,
            "posz": -2520.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 49",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8340.0,
            "posy": -2000.0,
            "posz": -1940.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4A",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 7410.0,
            "posy": -2000.0,
            "posz": -770.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4B",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 6870.0,
            "posy": -2000.0,
            "posz": -520.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4C",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 5400.0,
            "posy": -2000.0,
            "posz": -510.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4D",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 4840.0,
            "posy": -2000.0,
            "posz": -780.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4E",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 3930.0,
            "posy": -2000.0,
            "posz": -1940.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 4F",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 3790.0,
            "posy": -2000.0,
            "posz": -2520.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 50",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 5830.0,
            "posy": -2000.0,
            "posz": -5080.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 51",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 6430.0,
            "posy": -2000.0,
            "posz": -5080.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 52",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 7770.0,
            "posy": -2000.0,
            "posz": -4430.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 53",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 7F FF FF",
            "posx": 8140.0,
            "posy": -2000.0,
            "posz": -3960.0,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 54",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "3F FF FF FF",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 8,
            "tosky_scen_link": 63,
            "scen_link": -3,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 6131.0,
            "posy": 55.0,
            "posz": -2746.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20391,
            "unk3": "00 65",
            "name": "NpcAdr",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "08 3F FD FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 25,
            "tosky_scen_link": 1,
            "scen_link": 4,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 5310.0,
            "posy": -190.97265625,
            "posz": -3400.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20392,
            "unk3": "00 66",
            "name": "NpcAdr",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "19 01 04 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 32,
            "byte4": 100,
            "unk1": "FF FF FF FF",
            "posx": 5762.650390625,
            "posy": 50.0,
            "posz": -3040.0,
            "sizex": 3.4200000762939453,
            "sizey": 5.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 67",
            "name": "ClrWall",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF 20 64"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 5310.0,
            "posy": -190.97265625,
            "posz": -3400.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20392,
            "unk3": "00 65",
            "name": "NpcAdr",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF FC FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -16,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 5762.650390625,
            "posy": 50.0,
            "posz": -3040.0,
            "sizex": 3.4200000762939453,
            "sizey": 5.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 66",
            "name": "ClrWall",
            "angle": -28636,
            "extraInfo": {
                "first_4_bytes": "FF FF F0 FF"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 5350.0,
            "posy": -10.97265625,
            "posz": -3450.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 20392,
            "unk3": "00 65",
            "name": "NpcAdr",
            "angle": -28252,
            "extraInfo": {
                "first_4_bytes": "FF FF FC FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        }
    ]
});