/* eslint-disable */export default Object.freeze({
    "stageid": "F201_1",
    "stagename": "Eldin Volcano: Inside Volcano",
    "maxx": 5800.0,
    "minx": -7400.0,
    "maxz": 5800.0,
    "minz": -6100.0,
    "usedLayers": [
        "l0",
        "l2",
        "l3",
        "l4"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2950.0,
            "posy": -260.0,
            "posz": -700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2950.0,
            "posy": -260.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2100.0,
            "posy": -260.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2100.0,
            "posy": -260.0,
            "posz": -700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 900.0,
            "posy": 500.0,
            "posz": -6000.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 09",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 1200.0,
            "posy": 500.0,
            "posz": -3600.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 0A",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 3700.0,
            "posy": 500.0,
            "posz": -2500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 0B",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 4000.0,
            "posy": 500.0,
            "posz": -6100.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 0C",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 2700.0,
            "posy": 500.0,
            "posz": -4400.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 0D",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -64,
            "byte4": 1,
            "unk1": "25 DF FF FF",
            "posx": 2100.0,
            "posy": 500.0,
            "posz": -5500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -256,
            "unk3": "FC 0E",
            "name": "EKs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 3455.0,
            "posy": 65.0,
            "posz": -3900.0,
            "event_flag": -4,
            "transition_type": 114,
            "unk2": "20 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 107,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 3100.0,
            "posy": -50.0,
            "posz": -3500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "EMagupp",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 107,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 900.0,
            "posy": -50.0,
            "posz": -3300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "EMagupp",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 107,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -3400.0,
            "posy": -500.0,
            "posz": 1700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "EMagupp",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 107,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 1200.0,
            "posy": -50.0,
            "posz": -4500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "EMagupp",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 107,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -1800.0,
            "posy": -500.0,
            "posz": 1700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "EMagupp",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1000.0,
            "posy": 190.0,
            "posz": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FE",
            "posx": -300.0,
            "posy": 600.0,
            "posz": -500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "NpcInv",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1000.0,
            "posy": 190.0,
            "posz": -300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -1450.0,
            "posy": 0.0,
            "posz": 700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 4100.0,
            "posy": 50.0,
            "posz": -1900.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -27,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -22,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -19,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -11,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -14,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 5800.0,
            "posy": -100.0,
            "posz": -200.0,
            "event_flag": 3,
            "transition_type": -114,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 20",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -8,
            "unk1": "FF FF FF FF",
            "posx": -7400.0,
            "posy": 200.0,
            "posz": 2300.0,
            "event_flag": -8,
            "transition_type": -28,
            "unk2": "36 0B",
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -5,
            "unk1": "FF FF FF FF",
            "posx": -2400.0,
            "posy": -150.0,
            "posz": 5800.0,
            "event_flag": -8,
            "transition_type": -28,
            "unk2": "15 55",
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2500.0,
            "posy": -500.0,
            "posz": 1300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "SnkFlrF",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -2500.0,
            "posy": -500.0,
            "posz": 2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "SnkFlrF",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": 117,
            "unk1": "FF 5F FF FF",
            "posx": -400.0,
            "posy": 0.0,
            "posz": -700.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -1,
            "unk3": "FC 10",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 117,
                "areaflag": "scene flag: 0xF 20"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 8,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3740.0,
            "posy": -98.223876953125,
            "posz": 3100.0,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 2D",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2300.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 2E",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2400.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 2F",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2300.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 30",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2650.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 31",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2750.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 32",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2650.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 33",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3000.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 34",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3100.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 35",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3000.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 36",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 11,
            "scen_link": -1,
            "byte4": 16,
            "unk1": "FF DF FF FF",
            "posx": 1700.0,
            "posy": 1008.4671630859375,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 5,
            "unk3": "FC 37",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 11,
            "scen_link": -1,
            "byte4": 16,
            "unk1": "FF DF FF FF",
            "posx": 1700.0,
            "posy": 1077.134033203125,
            "posz": -100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 5,
            "unk3": "FC 38",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 11,
            "scen_link": -1,
            "byte4": 16,
            "unk1": "FF DF FF FF",
            "posx": 1300.0,
            "posy": 1075.4449462890625,
            "posz": -900.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 5,
            "unk3": "FC 39",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 11,
            "scen_link": -1,
            "byte4": 16,
            "unk1": "FF DF FF FF",
            "posx": 1100.0,
            "posy": 932.6868896484375,
            "posz": -100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 5,
            "unk3": "FC 3A",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 10,
            "scen_link": -1,
            "byte4": 16,
            "unk1": "FF DF FF FF",
            "posx": 700.0,
            "posy": 1233.8529052734375,
            "posz": -700.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 5,
            "unk3": "FC 3B",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -97,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "04 5F FF FF",
            "posx": -2500.0,
            "posy": -400.0,
            "posz": -400.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": 2314,
            "unk3": "FC 2D",
            "name": "ELizaru",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -113,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "04 5F FF FF",
            "posx": -2500.0,
            "posy": -400.0,
            "posz": -100.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": 2058,
            "unk3": "FC 2E",
            "name": "ELizaru",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": 23,
            "tosky_scen_link": 98,
            "scen_link": -24,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 2300.0,
            "posy": -200.0,
            "posz": -600.0,
            "event_flag": 0,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": 30344,
            "unk3": "FC 2F",
            "name": "NpcSlb2",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l3"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -3381.514892578125,
            "posy": -400.0,
            "posz": 203.2342987060547,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2F",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -3560.69287109375,
            "posy": -400.0,
            "posz": 55.42604064941406,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 30",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -3619.726806640625,
            "posy": -400.0,
            "posz": 277.307861328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 31",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -3,
            "unk1": "FF FF FF FF",
            "posx": 1314.69677734375,
            "posy": 50.0,
            "posz": -68.63192749023438,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "A0 00",
            "talk_behaviour": 0,
            "unk3": "FC 32",
            "name": "SwrdSt",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -111,
            "unk1": "07 FF FF FF",
            "posx": 1564.7620849609375,
            "posy": -150.0,
            "posz": -205.8795928955078,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 34",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -103,
                "areaflag": "temp flag: 0x2 02"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -95,
            "unk1": "07 FF FF FF",
            "posx": 1548.468994140625,
            "posy": -150.0,
            "posz": -307.7120361328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -102,
                "areaflag": "temp flag: 0x2 04"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -79,
            "unk1": "07 FF FF FF",
            "posx": 1515.8828125,
            "posy": -150.0,
            "posz": -433.98431396484375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 36",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -101,
                "areaflag": "temp flag: 0x2 08"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 0,
            "unk1": "08 FF FF FF",
            "posx": -2872.60009765625,
            "posy": -400.0,
            "posz": -1022.8760986328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 37",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -112,
                "areaflag": "temp flag: 0x3 01"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 16,
            "unk1": "08 FF FF FF",
            "posx": -2862.91552734375,
            "posy": -400.0,
            "posz": -1175.965087890625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 38",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -111,
                "areaflag": "temp flag: 0x3 02"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 32,
            "unk1": "08 FF FF FF",
            "posx": -3022.520263671875,
            "posy": -400.0,
            "posz": -1129.3709716796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 39",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -110,
                "areaflag": "temp flag: 0x3 04"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 48,
            "unk1": "08 FF FF FF",
            "posx": -2745.5673828125,
            "posy": -400.0,
            "posz": -1092.375244140625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3A",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -109,
                "areaflag": "temp flag: 0x3 08"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 64,
            "unk1": "08 FF FF FF",
            "posx": -2707.27978515625,
            "posy": -400.0,
            "posz": -1228.4835205078125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3B",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -108,
                "areaflag": "temp flag: 0x3 10"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 80,
            "unk1": "08 FF FF FF",
            "posx": -2569.593505859375,
            "posy": -400.0,
            "posz": -1084.7322998046875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3C",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -107,
                "areaflag": "temp flag: 0x3 20"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 96,
            "unk1": "08 FF FF FF",
            "posx": -3746.0263671875,
            "posy": -360.0,
            "posz": -348.15106201171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3D",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -106,
                "areaflag": "temp flag: 0x3 40"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": 112,
            "unk1": "08 FF FF FF",
            "posx": -3856.454345703125,
            "posy": -360.0,
            "posz": -398.345703125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3E",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -105,
                "areaflag": "temp flag: 0x3 80"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -128,
            "unk1": "08 FF FF FF",
            "posx": -3766.103759765625,
            "posy": -360.0,
            "posz": -463.5987854003906,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 3F",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -104,
                "areaflag": "temp flag: 0x2 01"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 47,
            "scen_link": 24,
            "byte4": -30,
            "unk1": "23 FF FF FF",
            "posx": -387.6276550292969,
            "posy": 0.0,
            "posz": -398.7879333496094,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 40",
            "name": "Soil",
            "extraInfo": {
                "flagid": -114,
                "areaflag": "temp flag: 0x0 40"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -3794.376220703125,
            "posy": -360.0,
            "posz": -650.3067016601562,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -29072,
            "unk3": "FC 2D",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 1604.59130859375,
            "posy": -150.0,
            "posz": 29.18498420715332,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -28669,
            "unk3": "FC 2E",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 9,
            "byte4": 43,
            "unk1": "FF 7F FF FF",
            "posx": -550.0,
            "posy": 550.0,
            "posz": 950.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 33",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": 43,
                "areaflag": "scene flag: 0x4 08"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2300.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 41",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2400.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 42",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2300.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 43",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2650.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 44",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2750.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 45",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -2650.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 46",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3000.0,
            "posy": -400.0,
            "posz": -500.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 47",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3100.0,
            "posy": -400.0,
            "posz": -200.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 48",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 6,
            "scen_link": -1,
            "byte4": 48,
            "unk1": "FF DF FF FF",
            "posx": -3000.0,
            "posy": -400.0,
            "posz": 100.0,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 10,
            "unk3": "FC 49",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l4"
        }
    ]
});