/* eslint-disable */export default Object.freeze({
    "stageid": "F201_4",
    "stagename": "Eldin Volcano: Volcano Summit - Waterfall",
    "maxx": 2600.0,
    "minx": -2000.0,
    "maxz": 4900.0,
    "minz": -1900.0,
    "usedLayers": [
        0,
        3
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -5,
            "unk1": "FF FF FF FF",
            "posx": 2600.0,
            "posy": -4055.5771484375,
            "posz": 4900.0,
            "event_flag": -8,
            "transition_type": -28,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "GodCube",
            "angle": 21781,
            "extraInfo": {
                "first_4_bytes": "F0 FF 00 FB"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 23,
            "tosky_scen_link": 71,
            "scen_link": 79,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 900.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 100,
            "transition_type": -1,
            "talk_behaviour": 30337,
            "unk3": "FC 03",
            "name": "NpcMoN",
            "angle": 22165,
            "extraInfo": {
                "first_4_bytes": "17 47 4F FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -14,
            "unk1": "FF 1F FF F0",
            "posx": 1000.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": -1,
            "transition_type": -64,
            "talk_behaviour": 30338,
            "unk3": "FC 04",
            "name": "NpcTke",
            "angle": -1,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F2"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -8,
            "byte4": -110,
            "unk1": "17 FF FF FF",
            "posx": 1550.0,
            "posy": 0.0,
            "posz": -70.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Soil",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF F8 92",
                "flagid": -119,
                "areaflag": "temp flag: 0x0 02"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -8,
            "byte4": -94,
            "unk1": "04 FF FF FF",
            "posx": 1760.0,
            "posy": 0.0,
            "posz": 40.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Soil",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF F8 A2",
                "flagid": -118,
                "areaflag": "temp flag: 0x0 04"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -16,
            "tosky_scen_link": 15,
            "scen_link": -1,
            "byte4": 118,
            "unk1": "FF DF FF FF",
            "posx": 1610.0,
            "posy": 648.2476196289062,
            "posz": -420.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 4104,
            "unk3": "FC 07",
            "name": "HrpHint",
            "angle": -21910,
            "extraInfo": {
                "first_4_bytes": "F0 0F FF 76",
                "flagid": 118,
                "areaflag": "scene flag: 0xF 40"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 2100.0,
            "posy": 670.732666015625,
            "posz": -680.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Bombf",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 1340.0,
            "posy": 812.68212890625,
            "posz": -1240.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -27,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 E5"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -22,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 EA"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -19,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 ED"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -11,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F5"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -14,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F2"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F0"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -8,
            "unk1": "FF FF FF FF",
            "posx": -2000.0,
            "posy": 100.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "GodCube",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "F1 FF 00 F8"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 0,
            "scen_link": 13,
            "byte4": 112,
            "unk1": "FF 7F FF FF",
            "posx": 2000.0,
            "posy": 800.0,
            "posz": -1700.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "BlsRock",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 00 0D 70",
                "flagid": 112,
                "areaflag": "scene flag: 0xF 01"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 2000.0,
            "posy": 800.0,
            "posz": -1900.0,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -16864,
            "unk3": "FC 02",
            "name": "TBox",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F3"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -117,
            "unk1": "23 7F FF FF",
            "posx": 690.0,
            "posy": 200.0,
            "posz": -1210.0,
            "sizex": 1.7999999523162842,
            "sizey": 1.7999999523162842,
            "sizez": 1.7999999523162842,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "0F FF FF 8B",
                "flagid": -117,
                "areaflag": "temp flag: 0x0 08"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 23,
            "tosky_scen_link": 98,
            "scen_link": -24,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 800.0,
            "posy": 0.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": -1,
            "talk_behaviour": 30345,
            "unk3": "FC 24",
            "name": "NpcSlb2",
            "angle": 192,
            "extraInfo": {
                "first_4_bytes": "17 62 E8 FF"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 3
        }
    ]
});