/* eslint-disable */export default Object.freeze({
    "stageid": "F201_3",
    "stagename": "Eldin Volcano: Fire Sanctuary Entrance",
    "maxx": 7500.0,
    "minx": -8500.0,
    "maxz": 1600.0,
    "minz": -13280.0,
    "usedLayers": [
        0,
        2,
        3
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF F8 12",
            "unk2": "17 FF FF FF",
            "posx": 1100.0,
            "posy": 0.0,
            "posz": -4700.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF F8 22",
            "unk2": "04 FF FF FF",
            "posx": 1200.0,
            "posy": 0.0,
            "posz": -4100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 69 76 5F",
            "unk2": "FF FF FF FF",
            "posx": 900.0,
            "posy": 300.0,
            "posz": -2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "KanbanS",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 600.0,
            "posy": 0.0,
            "posz": -3150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 800.0,
            "posy": 0.0,
            "posz": -3250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF F8 42",
            "unk2": "18 FF FF 6E",
            "posx": -1450.0,
            "posy": 0.0,
            "posz": -3430.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF F8 52",
            "unk2": "17 FF FF 6E",
            "posx": -1360.0,
            "posy": 0.0,
            "posz": -3280.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FC 62",
            "unk2": "FF FF FF FF",
            "posx": 540.0,
            "posy": 550.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "WaterSW",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FC 08 63",
            "unk2": "FF FF FF FF",
            "posx": -540.0,
            "posy": 250.0,
            "posz": -5200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "WaterSW",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FD 64",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 100.0,
            "posz": -10901.470703125,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "WaterSW",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F0 FF 00 F8",
            "unk2": "FF FF FF FF",
            "posx": -1200.0,
            "posy": 889.2900390625,
            "posz": -5600.0,
            "event_flag": 248,
            "transition_type": 228,
            "angle": 13835,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 01",
            "unk2": "FF FF FF FF",
            "posx": 2200.0,
            "posy": 0.0,
            "posz": -3600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "Uground",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF C3 FF 67",
            "unk2": "FF FF FF FF",
            "posx": 1800.0,
            "posy": 0.0,
            "posz": -4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "InHole",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 0D A2 5E",
            "unk2": "FF FF FF FF",
            "posx": 3200.0,
            "posy": 45.0,
            "posz": -4100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "Item",
            "extra_info": {
                "flagid": 104,
                "itemid": 94,
                "areaflag": "scene flag: 0xC 01",
                "item": "Heart piece"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "3A 83 3C FF",
            "unk2": "FF 5F FF FF",
            "posx": -300.0,
            "posy": 300.0,
            "posz": -2500.0,
            "event_flag": 3,
            "transition_type": 255,
            "angle": 24576,
            "talk_behaviour": 30305,
            "unk3": "FC 10",
            "name": "NpcGra",
            "extra_info": {
                "trigstoryfid": 207,
                "untrigstoryfid": 468,
                "trigstoryf": "Eldin Trial Completed (removes fi trigger in front of Volcano Summit)",
                "untrigstoryf": "Goron Text after Watering 1st Frog"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "3A A7 50 FF",
            "unk2": "FF 5F FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": -4800.0,
            "event_flag": 3,
            "transition_type": 255,
            "angle": 40960,
            "talk_behaviour": 30307,
            "unk3": "FC 11",
            "name": "NpcGra",
            "extra_info": {
                "trigstoryfid": 468,
                "untrigstoryfid": 469,
                "trigstoryf": "Goron Text after Watering 1st Frog",
                "untrigstoryf": "Goron Text after Watering 2nd frog"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "01 A7 54 FF",
            "unk2": "FF 5F FF FF",
            "posx": 500.0,
            "posy": -500.0,
            "posz": -10200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 39140,
            "talk_behaviour": 30309,
            "unk3": "FC 12",
            "name": "NpcGra",
            "extra_info": {
                "trigstoryfid": 469,
                "untrigstoryfid": 13,
                "trigstoryf": "Goron Text after Watering 2nd frog",
                "untrigstoryf": "Beat Fire Sanctuary (Sealed Temple layer 3 / Sealed Grounds layer 3 / Behind The Temple layer 4 / FS Boss Room layer 2 /  FS Entrance layer 4)"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FC 63",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -5300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "FireObs",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FC 74",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 300.0,
            "posz": -2900.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "FireObs",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FD 64",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -500.0,
            "posz": -11240.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "FireObs",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "01 FF FF FF",
            "posx": 2050.0,
            "posy": -500.0,
            "posz": -10950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 2250.0,
            "posy": -500.0,
            "posz": -10950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "01 FF FF FF",
            "posx": 2450.0,
            "posy": -500.0,
            "posz": -10950.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": 2150.0,
            "posy": -500.0,
            "posz": -11050.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": 2350.0,
            "posy": -500.0,
            "posz": -11050.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "01 FF FF FF",
            "posx": -2150.0,
            "posy": -500.0,
            "posz": -11100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": -2350.0,
            "posy": -500.0,
            "posz": -11100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "01 FF FF FF",
            "posx": -2050.0,
            "posy": -500.0,
            "posz": -11000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -2450.0,
            "posy": -500.0,
            "posz": -11000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -2250.0,
            "posy": -500.0,
            "posz": -11000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "08 FF FF FF",
            "posx": 2940.0,
            "posy": -98.30000305175781,
            "posz": -10530.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 20",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "08 FF FF FF",
            "posx": 2250.0,
            "posy": -98.30000305175781,
            "posz": -9840.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F0 8F FF F1",
            "unk2": "04 5F FF FF",
            "posx": -3400.0,
            "posy": 605.4400024414062,
            "posz": -7600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 1034,
            "unk3": "FC 22",
            "name": "ELizaru",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 1F F8 62",
            "unk2": "17 FF FF FF",
            "posx": -820.0,
            "posy": 799.2300415039062,
            "posz": -5780.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 23",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 06 22 02",
            "unk2": "FF FF FF FF",
            "posx": 2200.0,
            "posy": -149.0,
            "posz": -4800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 24",
            "name": "Item",
            "extra_info": {
                "flagid": 136,
                "itemid": 2,
                "areaflag": "temp flag: 0x0 01",
                "item": "green rupee"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 06 1E 03",
            "unk2": "FF FF FF FF",
            "posx": 1000.0,
            "posy": -149.0,
            "posz": -3600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "Item",
            "extra_info": {
                "flagid": 135,
                "itemid": 3,
                "areaflag": "temp flag: 0x1 80",
                "item": "Blue rupee"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1120.0,
            "posy": 0.0,
            "posz": -11090.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 26",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 1120.0,
            "posy": 0.0,
            "posz": -11090.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 27",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 470.0,
            "posy": -530.0,
            "posz": -12280.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 28",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -470.0,
            "posy": -530.0,
            "posz": -12280.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 29",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 470.0,
            "posy": -1050.0,
            "posz": -13280.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2A",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -470.0,
            "posy": -1050.0,
            "posz": -13280.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2B",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -700.0,
            "posy": 0.0,
            "posz": -5600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 2C",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 2248.2900390625,
            "posy": -445.0,
            "posz": -11149.7900390625,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2D",
            "name": "CharE",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF C3 FF 66",
            "unk2": "FF FF FF FF",
            "posx": 1000.0,
            "posy": 0.0,
            "posz": -4400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 2E",
            "name": "InHole",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F0 FF FF 77",
            "unk2": "FF DF FF FF",
            "posx": 1200.0,
            "posy": 0.0,
            "posz": -4400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 4117,
            "unk3": "FC 2F",
            "name": "HrpHint",
            "extra_info": {
                "flagid": 119,
                "areaflag": "scene flag: 0xF 80"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 E5",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 30",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 EA",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 31",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 ED",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 32",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 F5",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 33",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 F2",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 34",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 FF",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 FB",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 36",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "F1 FF 00 F0",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 37",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF F7 1A 72",
            "unk2": "FF FF FF FF",
            "posx": -800.0,
            "posy": 0.0,
            "posz": -3600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 38",
            "name": "Soil",
            "extra_info": {
                "flagid": 113,
                "areaflag": "scene flag: 0xF 02"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF 2A 82",
            "unk2": "04 FF FF FF",
            "posx": -600.0,
            "posy": 0.0,
            "posz": -3420.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 39",
            "name": "Soil",
            "extra_info": {
                "flagid": 242,
                "areaflag": "temp flag: 0xF 04"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "6E 03 0E 6E",
            "unk2": "FF 7F FF FF",
            "posx": -1280.0,
            "posy": 0.0,
            "posz": -3450.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 20935,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "BlsRock",
            "extra_info": {
                "flagid": 110,
                "areaflag": "scene flag: 0xC 40"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "02 02 01 65",
            "unk2": "FF 5F FF 0E",
            "posx": -600.0,
            "posy": -500.0,
            "posz": -10500.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 0B",
            "name": "saveObj",
            "extra_info": {
                "flagid": 101,
                "tosky_scen_link": 2,
                "areaflag": "scene flag: 0xD 20"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF F0 74",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 300.0,
            "posz": -2900.0,
            "sizex": 10.0,
            "sizey": 10.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 3A",
            "name": "ClrWall",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF F0 63",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": -5300.0,
            "sizex": 10.0,
            "sizey": 10.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 3B",
            "name": "ClrWall",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "2F F0 00 8C",
            "unk2": "12 7F FF FF",
            "posx": -1120.0,
            "posy": 0.0,
            "posz": -11030.0,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 4A",
            "name": "TgReact",
            "extra_info": {
                "flagid": 140,
                "itemid": 18,
                "areaflag": "temp flag: 0x0 10",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "2F F0 00 8D",
            "unk2": "12 7F FF FF",
            "posx": 1120.0,
            "posy": 0.0,
            "posz": -11030.0,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 4B",
            "name": "TgReact",
            "extra_info": {
                "flagid": 141,
                "itemid": 18,
                "areaflag": "temp flag: 0x0 20",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "1F F0 00 71",
            "unk2": "14 7F FF FF",
            "posx": 0.0,
            "posy": 350.0,
            "posz": -10750.0,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 4C",
            "name": "TgReact",
            "extra_info": {
                "flagid": 113,
                "itemid": 20,
                "areaflag": "scene flag: 0xF 02",
                "item": "Clawshots + Storyflag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF 00 00",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 200.0,
            "posz": 0.0,
            "sizex": 800.0,
            "sizey": 800.0,
            "sizez": 800.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 3C",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 06 01 01",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -900.0,
            "posz": -12100.0,
            "sizex": 1000.0,
            "sizey": 800.0,
            "sizez": 800.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 3D",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 64 60 00",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -1100.0,
            "posz": -11500.0,
            "sizex": 2000.0,
            "sizey": 2000.0,
            "sizez": 800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 3E",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": 1600.0,
            "posy": -240.0,
            "posz": -4300.0,
            "sizex": 2000.0,
            "sizey": 200.0,
            "sizez": 2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 3F",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF 08 01",
            "unk2": "FF DF FF FF",
            "posx": 1600.0,
            "posy": -240.0,
            "posz": -4300.0,
            "sizex": 2000.0,
            "sizey": 200.0,
            "sizez": 2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 40",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF DF FF FF",
            "posx": 2450.0,
            "posy": -10.0,
            "posz": -4000.0,
            "sizex": 2000.0,
            "sizey": 1000.0,
            "sizez": 1800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 41",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 05",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -700.0,
            "posz": -8500.0,
            "sizex": 7000.0,
            "sizey": 400.0,
            "sizez": 4200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 42",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 07",
            "unk2": "FF DF FF FF",
            "posx": 2200.0,
            "posy": -200.0,
            "posz": -9900.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 43",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 07",
            "unk2": "FF DF FF FF",
            "posx": -2250.0,
            "posy": -200.0,
            "posz": -9800.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 44",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 07",
            "unk2": "FF DF FF FF",
            "posx": 2900.0,
            "posy": -200.0,
            "posz": -10500.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 45",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 07",
            "unk2": "FF DF FF FF",
            "posx": -3000.0,
            "posy": -200.0,
            "posz": -10500.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 46",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": -1000.0,
            "posy": 2300.0,
            "posz": -7400.0,
            "sizex": 16000.0,
            "sizey": 1000.0,
            "sizez": 10000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 49",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF F6 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 4D",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF F7 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": 400.0,
            "posz": 1600.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 4E",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": -8500.0,
            "posy": -6771.5400390625,
            "posz": -7400.0,
            "sizex": 1000.0,
            "sizey": 10000.0,
            "sizez": 10000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 4F",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF C2",
            "unk2": "FF FF FF FF",
            "posx": 7500.0,
            "posy": -6771.5400390625,
            "posz": -7400.0,
            "sizex": 1000.0,
            "sizey": 10000.0,
            "sizez": 10000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 50",
            "name": "BtlTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF C4",
            "unk2": "FF FF FF FF",
            "posx": -3000.0,
            "posy": -200.0,
            "posz": -10500.0,
            "sizex": 500.0,
            "sizey": 500.0,
            "sizez": 500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 51",
            "name": "ActTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF 62 74 01",
            "unk2": "FF FF FF FF",
            "posx": 500.0,
            "posy": 200.0,
            "posz": -2400.0,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 52",
            "name": "EvntTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 0.0,
            "posy": -2000.0,
            "posz": -12800.0,
            "sizex": 1200.0,
            "sizey": 2400.0,
            "sizez": 1200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 53",
            "name": "SpkTg2",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF D6 83",
            "unk2": "FF FF FF FF",
            "posx": 2900.0,
            "posy": 0.0,
            "posz": -4100.0,
            "sizex": 400.0,
            "sizey": 200.0,
            "sizez": 400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 54",
            "name": "FairyTa",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF F7 74 A3",
            "unk2": "FF FF FF FF",
            "posx": 1200.0,
            "posy": 0.0,
            "posz": -4400.0,
            "sizex": 150.0,
            "sizey": 150.0,
            "sizez": 150.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 55",
            "name": "InsctTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF C3",
            "unk2": "FF FF FF FF",
            "posx": -800.0,
            "posy": 0.0,
            "posz": -3600.0,
            "sizex": 300.0,
            "sizey": 300.0,
            "sizez": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 56",
            "name": "InsctTg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F201_3"
        },
        {
            "unk1": "3A 9F FF 00",
            "unk2": "FF 1F FF FF",
            "posx": -300.0,
            "posy": 300.0,
            "posz": -2400.0,
            "event_flag": 255,
            "transition_type": 108,
            "angle": 65535,
            "talk_behaviour": 30306,
            "unk3": "FC 5A",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 468,
                "trigstoryf": "-",
                "untrigstoryf": "Goron Text after Watering 1st Frog",
                "trigscenefid": 108,
                "untrigscenefid": 255,
                "trigscenef": "scene flag: 0xC 10",
                "untrigscenef": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "3A BF FF 00",
            "unk2": "FF 1F FF FF",
            "posx": 300.0,
            "posy": 0.0,
            "posz": -4700.0,
            "event_flag": 255,
            "transition_type": 109,
            "angle": 65535,
            "talk_behaviour": 30308,
            "unk3": "FC 5B",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 469,
                "trigstoryf": "-",
                "untrigstoryf": "Goron Text after Watering 2nd frog",
                "trigscenefid": 109,
                "untrigscenefid": 255,
                "trigscenef": "scene flag: 0xC 20",
                "untrigscenef": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "3A 7F FF 00",
            "unk2": "FF 1F FF FF",
            "posx": 400.0,
            "posy": -500.0,
            "posz": -10100.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 65281,
            "talk_behaviour": 30309,
            "unk3": "FC 5C",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 467,
                "trigstoryf": "-",
                "untrigstoryf": "Goron Text near Big Frog",
                "trigscenefid": 255,
                "untrigscenefid": 255,
                "trigscenef": "no flag",
                "untrigscenef": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 1F FF FF",
            "posx": -200.0,
            "posy": 300.0,
            "posz": -2400.0,
            "event_flag": 107,
            "transition_type": 255,
            "angle": 65280,
            "talk_behaviour": 30304,
            "unk3": "FC 5D",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 107,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0xC 08"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "0D DF FF F2",
            "unk2": "FF 1F FF FF",
            "posx": 200.0,
            "posy": 300.0,
            "posz": -2400.0,
            "event_flag": 255,
            "transition_type": 192,
            "angle": 65535,
            "talk_behaviour": 30302,
            "unk3": "FC 5E",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 110,
                "trigstoryf": "-",
                "untrigstoryf": "Goddess Cube Dowsing",
                "trigscenefid": 192,
                "untrigscenefid": 255,
                "trigscenef": "temp flag: 0x9 01",
                "untrigscenef": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "53 A7 4F 03",
            "unk2": "FF 1F FF FF",
            "posx": 300.0,
            "posy": -500.0,
            "posz": -10100.0,
            "event_flag": 115,
            "transition_type": 255,
            "angle": 65282,
            "talk_behaviour": 30349,
            "unk3": "FC 5F",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 467,
                "untrigstoryfid": 669,
                "trigstoryf": "Goron Text near Big Frog",
                "untrigstoryf": "Water Basin Dowsing",
                "trigscenefid": 255,
                "untrigscenefid": 115,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0xF 08"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 06",
            "unk2": "FF DF FF FF",
            "posx": -610.0,
            "posy": 400.0,
            "posz": -5200.0,
            "sizex": 300.0,
            "sizey": 300.0,
            "sizez": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65379,
            "unk3": "FC 60",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F201_3"
        },
        {
            "unk1": "17 62 EB FB",
            "unk2": "FF 1F FF FF",
            "posx": -100.0,
            "posy": -500.0120544433594,
            "posz": -9400.0,
            "event_flag": 156,
            "transition_type": 255,
            "angle": 1027,
            "talk_behaviour": 30350,
            "unk3": "FC 5B",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 186,
                "untrigstoryfid": 187,
                "trigstoryf": "Water Basin collected (unsets when scrapper picks up anything else)",
                "untrigstoryf": "Big Frog Watered",
                "trigscenefid": 255,
                "untrigscenefid": 156,
                "trigscenef": "no flag",
                "untrigscenef": "temp flag: 0x2 10"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F201_3"
        },
        {
            "unk1": "17 62 EB F3",
            "unk2": "FF 1F FF FF",
            "posx": -200.0,
            "posy": -500.0120544433594,
            "posz": -9400.0,
            "event_flag": 157,
            "transition_type": 255,
            "angle": 65285,
            "talk_behaviour": 30350,
            "unk3": "FC 5C",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 186,
                "untrigstoryfid": 187,
                "trigstoryf": "Water Basin collected (unsets when scrapper picks up anything else)",
                "untrigstoryf": "Big Frog Watered",
                "trigscenefid": 255,
                "untrigscenefid": 157,
                "trigscenef": "no flag",
                "untrigscenef": "temp flag: 0x2 20"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F201_3"
        },
        {
            "unk1": "17 62 E8 FF",
            "unk2": "FF 5F FF FF",
            "posx": 500.0,
            "posy": 300.0,
            "posz": -1500.0,
            "event_flag": 0,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 30346,
            "unk3": "FC 5A",
            "name": "NpcSlb2",
            "extra_info": {
                "trigstoryfid": 186,
                "untrigstoryfid": 187,
                "trigstoryf": "Water Basin collected (unsets when scrapper picks up anything else)",
                "untrigstoryf": "Big Frog Watered"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F201_3"
        },
        {
            "unk1": "FF FF FF 9C",
            "unk2": "FF 5F FF FF",
            "posx": 0.0,
            "posy": -600.0,
            "posz": -8500.0,
            "sizex": 800.0,
            "sizey": 800.0,
            "sizez": 800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 5D",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F201_3"
        }
    ]
});