/* eslint-disable */export default Object.freeze({
    "stageid": "F210",
    "stagename": "Eldin Volcano: Caves",
    "maxx": 3910.0,
    "minx": -6750.0,
    "maxz": 8100.0,
    "minz": -3200.0,
    "usedLayers": [
        0,
        1,
        2,
        3,
        4
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1110.0,
            "posy": -7130.0,
            "posz": 8100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 00",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -2840.0,
            "posy": -7010.0,
            "posz": 5620.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 02",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -3400.0,
            "posy": -7010.0,
            "posz": 5620.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 03",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -2040.0,
            "posy": -6360.0,
            "posz": -1880.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -2040.0,
            "posy": -6360.0,
            "posz": -840.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 1060.0,
            "posy": -6920.0,
            "posz": 2380.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 07",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 1050.0,
            "posy": -6920.0,
            "posz": 3170.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 08",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -510.0,
            "posy": -7050.0,
            "posz": 3530.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 09",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1370.0,
            "posy": -7030.0,
            "posz": 2420.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0A",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1500.0,
            "posy": -7060.0,
            "posz": 3310.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0B",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -4550.0,
            "posy": -6240.0,
            "posz": 5690.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0C",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -5205.0,
            "posy": -5215.0,
            "posz": 7430.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0D",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -5915.0,
            "posy": -5200.0,
            "posz": 6460.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0E",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -5940.0,
            "posy": -5220.0,
            "posz": 5330.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 0F",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF F0 FF",
            "unk2": "FF FF FF FF",
            "posx": 1980.0,
            "posy": -6539.5400390625,
            "posz": 3450.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "00 12",
            "name": "Heartf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF F0 FF",
            "unk2": "FF FF FF FF",
            "posx": 1940.0,
            "posy": -6539.5400390625,
            "posz": 3640.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "00 13",
            "name": "Heartf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F 38 A2",
            "unk2": "17 FF FF FF",
            "posx": 2900.0,
            "posy": -4461.8603515625,
            "posz": 4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 14",
            "name": "Soil",
            "extra_info": {
                "flagid": 243,
                "areaflag": "temp flag: 0xF 08"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F 38 B2",
            "unk2": "18 FF FF FF",
            "posx": 3000.0,
            "posy": -4461.8603515625,
            "posz": 4300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 15",
            "name": "Soil",
            "extra_info": {
                "flagid": 243,
                "areaflag": "temp flag: 0xF 08"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F6",
            "unk2": "FF 5F FF FF",
            "posx": -5100.0,
            "posy": -6950.0,
            "posz": 1100.0,
            "event_flag": 255,
            "transition_type": 163,
            "angle": 3640,
            "talk_behaviour": 30009,
            "unk3": "FC 16",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L69"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 3300.0,
            "posy": -5993.6103515625,
            "posz": 3500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 17",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF FF FF FF",
            "posx": 3500.0,
            "posy": -5993.6103515625,
            "posz": 3500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 18",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 1300.0,
            "posy": -6830.0,
            "posz": -1900.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 52793,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": 3910.0,
            "posy": -7190.0,
            "posz": 200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 22755,
            "talk_behaviour": 0,
            "unk3": "00 1A",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -4430.0,
            "posy": -6805.5302734375,
            "posz": 5710.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "00 1B",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F0 FF F0",
            "unk2": "FF FF FF FF",
            "posx": -6600.0,
            "posy": -6950.0,
            "posz": -1450.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -4150.0,
            "posy": -6950.0,
            "posz": -750.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 20",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -4050.0,
            "posy": -6950.0,
            "posz": 450.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -2750.0,
            "posy": -6950.0,
            "posz": -750.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 16384,
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -2900.0,
            "posy": -6950.0,
            "posz": -1925.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 23",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F0 FF F0",
            "unk2": "FF FF FF FF",
            "posx": -2260.0,
            "posy": -6950.0,
            "posz": 410.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 24",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -4100.0,
            "posy": -6950.0,
            "posz": -2100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F F9 32",
            "unk2": "18 FF FF FF",
            "posx": 500.0,
            "posy": -6827.5703125,
            "posz": 7800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 27",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 32",
            "unk2": "17 FF FF FF",
            "posx": 700.0,
            "posy": -6830.0,
            "posz": -200.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 28",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 42",
            "unk2": "17 FF FF FF",
            "posx": 1300.0,
            "posy": -6830.0,
            "posz": -1700.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 29",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 52",
            "unk2": "17 FF FF FF",
            "posx": 1100.0,
            "posy": -6830.0,
            "posz": -2000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2A",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 62",
            "unk2": "17 FF FF FF",
            "posx": -4900.0,
            "posy": -5590.0,
            "posz": 7400.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 2B",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 72",
            "unk2": "07 FF FF FF",
            "posx": -4600.0,
            "posy": -5590.0,
            "posz": 7500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 2C",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -6600.0,
            "posy": -5590.0,
            "posz": 6600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2D",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FC E4",
            "unk2": "FF FF FF FF",
            "posx": -5730.0,
            "posy": -5590.0,
            "posz": 7500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 20024,
            "talk_behaviour": 0,
            "unk3": "00 2E",
            "name": "Char",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -6300.0,
            "posy": -5590.0,
            "posz": 4800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 2F",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -6300.0,
            "posy": -5590.0,
            "posz": 4900.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 30",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "07 FF FF FF",
            "posx": -6200.0,
            "posy": -5590.0,
            "posz": 4700.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 31",
            "name": "Tubo",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F 1A 33",
            "unk2": "FF FF FF FF",
            "posx": -5100.0,
            "posy": -6950.0,
            "posz": 1100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 32",
            "name": "Soil",
            "extra_info": {
                "flagid": 241,
                "areaflag": "temp flag: 0xF 02"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FF 82",
            "unk2": "17 FF FF FF",
            "posx": -5900.0,
            "posy": -6950.0,
            "posz": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 33",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F0 FF F0",
            "unk2": "FF FF FF FF",
            "posx": -2380.0,
            "posy": -6950.0,
            "posz": 350.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 34",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F0 FF F0",
            "unk2": "FF FF FF FF",
            "posx": -6650.0,
            "posy": -6950.0,
            "posz": -1250.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F 3F 92",
            "unk2": "04 FF FF FF",
            "posx": -5300.0,
            "posy": -6950.0,
            "posz": -900.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 36",
            "name": "Soil",
            "extra_info": {
                "flagid": 243,
                "areaflag": "temp flag: 0xF 08"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0F FB 62",
            "unk2": "18 FF FF FF",
            "posx": -2600.0,
            "posy": -7210.0,
            "posz": 2820.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 37",
            "name": "Soil",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -1105.0,
            "posy": -7100.0,
            "posz": 4910.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 38",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF FF FF FF",
            "posx": -300.0,
            "posy": -7100.0,
            "posz": 4910.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 39",
            "name": "Fire",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0E A6 04",
            "unk2": "FF FF FF FF",
            "posx": -4050.0,
            "posy": -6950.0,
            "posz": 450.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 49152,
            "talk_behaviour": 0,
            "unk3": "FC 3A",
            "name": "Item",
            "extra_info": {
                "flagid": 169,
                "itemid": 4,
                "areaflag": "temp flag: 0x4 02",
                "item": "Red Rupee"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF 1F FF FF",
            "posx": -5300.0,
            "posy": -7020.0,
            "posz": -2600.0,
            "event_flag": 80,
            "transition_type": 79,
            "angle": 65535,
            "talk_behaviour": 30032,
            "unk3": "FC 3B",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 79,
                "untrigscenefid": 80,
                "trigscenef": "scene flag: 0x8 80",
                "untrigscenef": "scene flag: 0xB 01",
                "eventSrc": "300-Mountain.c#L327"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "3A E0 37 FF",
            "unk2": "FF 5F FF FC",
            "posx": 2800.0,
            "posy": -6405.98046875,
            "posz": 1800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 30339,
            "unk3": "FC 3C",
            "name": "NpcMoEl",
            "extra_info": {
                "trigstoryfid": 13,
                "untrigstoryfid": 471,
                "trigstoryf": "Beat Fire Sanctuary (Sealed Temple layer 3 / Sealed Grounds layer 3 / Behind The Temple layer 4 / FS Boss Room layer 2 /  FS Entrance layer 4)",
                "untrigstoryf": "delivered something to the sky? (unsets on next request?)",
                "eventSrc": "303-MountainF2.c#L385"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF E0 37 FF",
            "unk2": "FF DF FF FF",
            "posx": 2800.0,
            "posy": -7020.0,
            "posz": 4100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 32768,
            "talk_behaviour": 30340,
            "unk3": "FC 3D",
            "name": "NpcMoT",
            "extra_info": {
                "trigstoryfid": 13,
                "untrigstoryfid": 2047,
                "trigstoryf": "Beat Fire Sanctuary (Sealed Temple layer 3 / Sealed Grounds layer 3 / Behind The Temple layer 4 / FS Boss Room layer 2 /  FS Entrance layer 4)",
                "untrigstoryf": "-",
                "eventSrc": "303-MountainF2.c#L431"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF E0 37 FF",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -6830.0,
            "posz": -700.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 36409,
            "talk_behaviour": 30341,
            "unk3": "FC 3E",
            "name": "NpcMoT2",
            "extra_info": {
                "trigstoryfid": 13,
                "untrigstoryfid": 2047,
                "trigstoryf": "Beat Fire Sanctuary (Sealed Temple layer 3 / Sealed Grounds layer 3 / Behind The Temple layer 4 / FS Boss Room layer 2 /  FS Entrance layer 4)",
                "untrigstoryf": "-",
                "eventSrc": "303-MountainF2.c#L515"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F0 FF 00 FF",
            "unk2": "FF FF FF FF",
            "posx": 3500.0,
            "posy": -5409.41015625,
            "posz": 2300.0,
            "event_flag": 3,
            "transition_type": 142,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 3F",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 E5",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 40",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 EA",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 41",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 ED",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 42",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 F5",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 43",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 F2",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 44",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 FB",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 45",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 F0",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 46",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "F1 FF 00 F8",
            "unk2": "FF FF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 47",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -3000.0,
            "posy": -6957.48046875,
            "posz": 4800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65080,
            "unk3": "00 01",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 56,
                "chestid": 127,
                "item": "Digging Mitts"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF 00 25",
            "unk2": "FF 5F FF FF",
            "posx": 1200.0,
            "posy": -7390.0,
            "posz": 1700.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 10012,
            "talk_behaviour": 65535,
            "unk3": "00 04",
            "name": "saveObj",
            "extra_info": {
                "flagid": 37,
                "tosky_scen_link": 255,
                "areaflag": "scene flag: 0x5 20"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 1310.0,
            "posy": -3616.1826171875,
            "posz": 2060.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 10922,
            "talk_behaviour": 32933,
            "unk3": "00 10",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 165,
                "chestid": 64,
                "item": "Eldin Ore"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": 3150.0,
            "posy": -7020.0,
            "posz": 5150.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 33344,
            "unk3": "00 11",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 64,
                "chestid": 65,
                "item": "Blue Bird Feather, Golden Skull or Goddess Plume"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -4700.0,
            "posy": -6950.0,
            "posz": -3200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 35872,
            "unk3": "FC 1C",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 32,
                "chestid": 70,
                "item": " Silver rupee"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 00 0F 33",
            "unk2": "FF 7F FF FF",
            "posx": 3150.0,
            "posy": -7020.0,
            "posz": 4750.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "00 1D",
            "name": "BlsRock",
            "extra_info": {
                "flagid": 51,
                "areaflag": "scene flag: 0x7 08"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 01 0F 2C",
            "unk2": "FF 7F FF FF",
            "posx": -4700.0,
            "posy": -6950.0,
            "posz": -2850.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "BlsRock",
            "extra_info": {
                "flagid": 44,
                "areaflag": "scene flag: 0x4 10"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -100.0,
            "posy": -7085.0400390625,
            "posz": 6500.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 49152,
            "talk_behaviour": 34981,
            "unk3": "00 26",
            "name": "TBox",
            "extra_info": {
                "spawnscenefid": 255,
                "spawnscenef": "no flag",
                "trigscenefid": 255,
                "trigscenef": "no flag",
                "itemid": 165,
                "chestid": 68,
                "item": "Eldin Ore"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "7F FF F0 07",
            "unk2": "FF DF FF FF",
            "posx": -1300.0,
            "posy": -7610.0,
            "posz": 2800.0,
            "sizex": 1.5,
            "sizey": 5.0,
            "sizez": 1.5,
            "event_flag": 1,
            "transition_type": 108,
            "angle": 49152,
            "talk_behaviour": 1023,
            "unk3": "00 48",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "7F FF F0 17",
            "unk2": "FF DF FF FF",
            "posx": 400.0,
            "posy": -6830.0,
            "posz": -900.0,
            "sizex": 2.0,
            "sizey": 6.0,
            "sizez": 2.0,
            "event_flag": 1,
            "transition_type": 108,
            "angle": 16384,
            "talk_behaviour": 1023,
            "unk3": "FC 49",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F6",
            "unk2": "FF DF FF FF",
            "posx": 1500.0,
            "posy": -6336.0703125,
            "posz": -800.0,
            "sizex": 10.0,
            "sizey": 30.0,
            "sizez": 10.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 771,
            "unk3": "FC 4A",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F6",
            "unk2": "FF DF FF FF",
            "posx": 3600.0,
            "posy": -7385.35009765625,
            "posz": -400.0,
            "sizex": 10.0,
            "sizey": 50.0,
            "sizez": 10.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 769,
            "unk3": "00 4B",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "7F FF F2 37",
            "unk2": "FF DF FF FF",
            "posx": -4100.0,
            "posy": -6805.5302734375,
            "posz": 5300.0,
            "sizex": 2.0,
            "sizey": 6.0,
            "sizez": 2.0,
            "event_flag": 1,
            "transition_type": 108,
            "angle": 0,
            "talk_behaviour": 1023,
            "unk3": "00 4C",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "7F FF F3 C7",
            "unk2": "FF DF FF FF",
            "posx": 0.0,
            "posy": -7512.97021484375,
            "posz": 7800.0,
            "sizex": 2.0,
            "sizey": 7.0,
            "sizez": 2.0,
            "event_flag": 1,
            "transition_type": 108,
            "angle": 16384,
            "talk_behaviour": 1023,
            "unk3": "00 4D",
            "name": "Wind",
            "extra_info": {
                "flagid": 255,
                "areaflag": "no flag"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F F1 00 C8",
            "unk2": "04 7F FF FF",
            "posx": -5112.88134765625,
            "posy": -5485.0,
            "posz": 6567.45947265625,
            "sizex": 1.5,
            "sizey": 1.5,
            "sizez": 1.5,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 53340,
            "talk_behaviour": 0,
            "unk3": "FC 65",
            "name": "TgReact",
            "extra_info": {
                "flagid": 200,
                "itemid": 4,
                "areaflag": "temp flag: 0x8 01",
                "item": "Red Rupee"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "1F F0 FF C9",
            "unk2": "12 7F FF FF",
            "posx": -5905.99169921875,
            "posy": -5247.1123046875,
            "posz": 6202.9482421875,
            "sizex": 1.0,
            "sizey": 1.5,
            "sizez": 1.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 66",
            "name": "TgReact",
            "extra_info": {
                "flagid": 201,
                "itemid": 18,
                "areaflag": "temp flag: 0x8 02",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F F0 00 CA",
            "unk2": "12 7F FF FF",
            "posx": -6310.0,
            "posy": -5332.54736328125,
            "posz": 4800.0,
            "sizex": 0.800000011920929,
            "sizey": 0.800000011920929,
            "sizez": 0.800000011920929,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 5461,
            "talk_behaviour": 0,
            "unk3": "FC 67",
            "name": "TgReact",
            "extra_info": {
                "flagid": 202,
                "itemid": 18,
                "areaflag": "temp flag: 0x8 04",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F F0 00 CB",
            "unk2": "12 7F FF FF",
            "posx": -6750.0,
            "posy": -5382.54736328125,
            "posz": 6220.0,
            "sizex": 0.800000011920929,
            "sizey": 0.800000011920929,
            "sizez": 0.800000011920929,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 12743,
            "talk_behaviour": 0,
            "unk3": "FC 68",
            "name": "TgReact",
            "extra_info": {
                "flagid": 203,
                "itemid": 18,
                "areaflag": "temp flag: 0x8 08",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F F0 00 CC",
            "unk2": "12 7F FF FF",
            "posx": -5760.0,
            "posy": -5382.54736328125,
            "posz": 7660.0,
            "sizex": 0.800000011920929,
            "sizey": 0.800000011920929,
            "sizez": 0.800000011920929,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 20024,
            "talk_behaviour": 0,
            "unk3": "FC 69",
            "name": "TgReact",
            "extra_info": {
                "flagid": 204,
                "itemid": 18,
                "areaflag": "temp flag: 0x8 10",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "0F F0 FF CD",
            "unk2": "12 7F FF FF",
            "posx": -5546.2646484375,
            "posy": -5404.04736328125,
            "posz": 7740.0,
            "sizex": 0.800000011920929,
            "sizey": 0.800000011920929,
            "sizez": 0.800000011920929,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 0,
            "unk3": "FC 6A",
            "name": "TgReact",
            "extra_info": {
                "flagid": 205,
                "itemid": 18,
                "areaflag": "temp flag: 0x8 20",
                "item": "?"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 01 FF 00",
            "unk2": "FF 5F FF FF",
            "posx": 3600.0,
            "posy": -6000.0,
            "posz": -400.0,
            "sizex": 800.0,
            "sizey": 3000.0,
            "sizez": 800.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 4E",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 01 FF 01",
            "unk2": "FF 5F FF FF",
            "posx": 1500.0,
            "posy": -5000.0,
            "posz": -800.0,
            "sizex": 800.0,
            "sizey": 3000.0,
            "sizez": 800.0,
            "event_flag": 231,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 4F",
            "name": "ScChang",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF AE",
            "unk2": "FF 5F FF FF",
            "posx": 3600.0,
            "posy": -6100.0,
            "posz": -400.0,
            "sizex": 800.0,
            "sizey": 100.0,
            "sizez": 800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 50",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF AF",
            "unk2": "FF 5F FF FF",
            "posx": 1500.0,
            "posy": -5100.0,
            "posz": -800.0,
            "sizex": 800.0,
            "sizey": 100.0,
            "sizez": 800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 51",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF DF FF FF",
            "posx": -6080.0,
            "posy": -5700.0,
            "posz": 4990.0,
            "sizex": 420.0,
            "sizey": 600.0,
            "sizez": 420.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 52",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF DF FF FF",
            "posx": -6401.80615234375,
            "posy": -5700.0,
            "posz": 6409.88037109375,
            "sizex": 420.0,
            "sizey": 600.0,
            "sizez": 420.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 53",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 02",
            "unk2": "FF DF FF FF",
            "posx": -5568.62451171875,
            "posy": -5700.0,
            "posz": 7439.8173828125,
            "sizex": 420.0,
            "sizey": 600.0,
            "sizez": 420.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 54",
            "name": "Cam2Tag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF C0",
            "unk2": "FF FF FF FF",
            "posx": -4200.0,
            "posy": -7100.0,
            "posz": -900.0,
            "sizex": 6000.0,
            "sizey": 2000.0,
            "sizez": 6000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5A",
            "name": "V_Clip",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF C0",
            "unk2": "FF FF FF FF",
            "posx": 400.0,
            "posy": -7100.0,
            "posz": -1200.0,
            "sizex": 4000.0,
            "sizey": 3000.0,
            "sizez": 3000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5B",
            "name": "V_Clip",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -5300.0,
            "posy": -7000.0,
            "posz": -1750.0,
            "sizex": 300.0,
            "sizey": 400.0,
            "sizez": 600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5D",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -4100.0,
            "posy": -7000.0,
            "posz": -2150.0,
            "sizex": 300.0,
            "sizey": 400.0,
            "sizez": 600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5E",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -2900.0,
            "posy": -7000.0,
            "posz": -1750.0,
            "sizex": 300.0,
            "sizey": 400.0,
            "sizez": 600.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 5F",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -2700.0,
            "posy": -7000.0,
            "posz": -750.0,
            "sizex": 600.0,
            "sizey": 400.0,
            "sizez": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 60",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -4300.0,
            "posy": -7000.0,
            "posz": -750.0,
            "sizex": 600.0,
            "sizey": 400.0,
            "sizez": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 61",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF FF",
            "unk2": "FF FF FF FF",
            "posx": -3900.0,
            "posy": -7000.0,
            "posz": 450.0,
            "sizex": 600.0,
            "sizey": 400.0,
            "sizez": 300.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 62",
            "name": "CBomSld",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F6 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 64",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF F4 FF FF",
            "unk2": "FF DF FF FF",
            "posx": 1500.0,
            "posy": 5000.0,
            "posz": -2800.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 6B",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF 46 01 00",
            "unk2": "FF 7F FF FF",
            "posx": 2700.0,
            "posy": -600.0,
            "posz": 2800.0,
            "sizex": 5000.0,
            "sizey": 5000.0,
            "sizez": 5000.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 6C",
            "name": "PltChg",
            "type": "STAG",
            "roomid": 0,
            "layerid": 0,
            "stageid": "F210"
        },
        {
            "unk1": "FF EF FF F2",
            "unk2": "25 FF FF FF",
            "posx": -5300.0,
            "posy": -6950.0,
            "posz": -1925.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "FC 6D",
            "name": "EHidoK",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F5",
            "unk2": "FF 5F FE FF",
            "posx": -900.0,
            "posy": -7610.0,
            "posz": 3950.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 2730,
            "talk_behaviour": 30004,
            "unk3": "00 6E",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L482"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 00",
            "unk2": "FF 1F FF FF",
            "posx": -837.1810302734375,
            "posy": -7506.30078125,
            "posz": 3653.758056640625,
            "event_flag": 2,
            "transition_type": 255,
            "angle": 65280,
            "talk_behaviour": 30002,
            "unk3": "00 6F",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 255,
                "untrigscenefid": 2,
                "trigscenef": "no flag",
                "untrigscenef": "scene flag: 0x1 04",
                "eventSrc": "300-Mountain.c#L413"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 10",
            "unk2": "FF 1F FF FF",
            "posx": -900.0,
            "posy": -7610.0,
            "posz": 3900.0,
            "event_flag": 3,
            "transition_type": 67,
            "angle": 65281,
            "talk_behaviour": 30003,
            "unk3": "00 70",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 67,
                "untrigscenefid": 3,
                "trigscenef": "scene flag: 0x9 08",
                "untrigscenef": "scene flag: 0x1 08",
                "eventSrc": "300-Mountain.c#L429"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 11",
            "unk2": "FF 1F FF FF",
            "posx": -800.0,
            "posy": -7610.0,
            "posz": 3950.0,
            "event_flag": 67,
            "transition_type": 4,
            "angle": 65535,
            "talk_behaviour": 30020,
            "unk3": "00 71",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 4,
                "untrigscenefid": 67,
                "trigscenef": "scene flag: 0x1 10",
                "untrigscenef": "scene flag: 0x9 08",
                "eventSrc": "300-Mountain.c#L470"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F6 FF F0 15",
            "unk2": "25 5F FF FF",
            "posx": -3050.0,
            "posy": -7195.263671875,
            "posz": 5750.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 16384,
            "talk_behaviour": 65441,
            "unk3": "00 72",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F0 FF FF 15",
            "unk2": "25 5F FF FF",
            "posx": -1000.0,
            "posy": -7320.1201171875,
            "posz": 7400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65442,
            "unk3": "00 73",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F0 FF FF 05",
            "unk2": "25 5F FF FF",
            "posx": -700.0,
            "posy": -7813.2939453125,
            "posz": 6300.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65444,
            "unk3": "00 74",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F8 FF F0 00",
            "unk2": "25 5F FF FF",
            "posx": -1450.0,
            "posy": -6412.84033203125,
            "posz": 5960.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 18204,
            "talk_behaviour": 65535,
            "unk3": "00 75",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F8 FF F0 00",
            "unk2": "25 5F FF FF",
            "posx": -1900.0,
            "posy": -6426.119140625,
            "posz": 7600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65535,
            "unk3": "00 76",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F2 FF FC 10",
            "unk2": "25 5F FF FF",
            "posx": -5900.0,
            "posy": -5590.0,
            "posz": 6200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 20024,
            "talk_behaviour": 65535,
            "unk3": "00 77",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F2 FF FF 00",
            "unk2": "25 5F FF FF",
            "posx": -1200.0,
            "posy": -7598.583984375,
            "posz": 6900.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65445,
            "unk3": "00 78",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F0 FF FF 00",
            "unk2": "25 5F FF FF",
            "posx": -1400.0,
            "posy": -7770.6201171875,
            "posz": 6400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 65446,
            "unk3": "00 79",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F0 FF FF 00",
            "unk2": "25 5F FF FF",
            "posx": -2100.0,
            "posy": -7644.56201171875,
            "posz": 6700.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 27306,
            "talk_behaviour": 65447,
            "unk3": "00 7A",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 07",
            "unk2": "FF 1F FF FF",
            "posx": -700.0,
            "posy": -7610.0,
            "posz": 3950.0,
            "event_flag": 4,
            "transition_type": 209,
            "angle": 65282,
            "talk_behaviour": 30007,
            "unk3": "00 7B",
            "name": "NpcTke",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "trigscenefid": 209,
                "untrigscenefid": 4,
                "trigscenef": "temp flag: 0xB 02",
                "untrigscenef": "scene flag: 0x1 10",
                "eventSrc": "300-Mountain.c#L18"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF 0A C0 30",
            "unk2": "FF DF FF FF",
            "posx": 2800.0,
            "posy": -6405.98046875,
            "posz": 1800.0,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 2,
            "unk3": "00 7C",
            "name": "ESm",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF C0",
            "unk2": "FF 5F FF FF",
            "posx": 2800.0,
            "posy": -6505.98046875,
            "posz": 1800.0,
            "sizex": 800.0,
            "sizey": 1000.0,
            "sizez": 800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "00 7D",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF D1",
            "unk2": "FF 5F FF FF",
            "posx": -1300.0,
            "posy": -8000.0,
            "posz": 5500.0,
            "sizex": 3600.0,
            "sizey": 300.0,
            "sizez": 1200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 7E",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "F6 3F F0 40",
            "unk2": "FF 7F FF FF",
            "posx": -1200.0,
            "posy": -7957.48046875,
            "posz": 6900.0,
            "sizex": 4800.0,
            "sizey": 1200.0,
            "sizez": 4800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 0,
            "unk3": "00 7F",
            "name": "DieTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FA FF 03",
            "unk2": "FF DF FF FF",
            "posx": -6500.0,
            "posy": -5900.0,
            "posz": 2100.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 80",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "80 7A 74 FF",
            "unk2": "FF DF FF FF",
            "posx": 1900.0,
            "posy": -2800.0,
            "posz": -1300.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 81",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FA 03 74",
            "unk2": "FF DF FF FF",
            "posx": 100.0,
            "posy": -5630.7578125,
            "posz": -1400.0,
            "sizex": 100.0,
            "sizey": 100.0,
            "sizez": 100.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 82",
            "name": "Dowsing",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 74",
            "unk2": "FF 5F FF FF",
            "posx": -2250.0,
            "posy": -7000.0,
            "posz": -1500.0,
            "sizex": 1000.0,
            "sizey": 1000.0,
            "sizez": 1200.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 83",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF 06",
            "unk2": "FF DF FF FF",
            "posx": -1500.0,
            "posy": -8100.0,
            "posz": 6900.0,
            "sizex": 4000.0,
            "sizey": 1000.0,
            "sizez": 4000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 84",
            "name": "CamTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF DF FF 03",
            "unk2": "FF DF FF FF",
            "posx": -1400.0,
            "posy": -8000.0,
            "posz": 6000.0,
            "sizex": 4400.0,
            "sizey": 1200.0,
            "sizez": 5800.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 0,
            "talk_behaviour": 1233,
            "unk3": "FC 85",
            "name": "PlRsTag",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FE FF D3",
            "unk2": "FF 5F FF FF",
            "posx": -100.0,
            "posy": -7700.0,
            "posz": 3200.0,
            "sizex": 3000.0,
            "sizey": 600.0,
            "sizez": 2400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 0,
            "talk_behaviour": 65535,
            "unk3": "FC 86",
            "name": "SwAreaT",
            "type": "STAG",
            "roomid": 0,
            "layerid": 1,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF 5F FF FF",
            "posx": -5460.0,
            "posy": -5590.0,
            "posz": 7440.0,
            "event_flag": 255,
            "transition_type": 206,
            "angle": 50973,
            "talk_behaviour": 30023,
            "unk3": "FC 6D",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F5",
            "unk2": "FF 5F FF FF",
            "posx": -1200.0,
            "posy": -7610.0,
            "posz": 3400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 18204,
            "talk_behaviour": 30024,
            "unk3": "FC 6E",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -4900.0,
            "posy": -5590.0,
            "posz": 6800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 40960,
            "talk_behaviour": 30025,
            "unk3": "FC 6F",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L64"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "FF E0 3F F1",
            "unk2": "FF 5F FF FF",
            "posx": -5200.0,
            "posy": -6950.0,
            "posz": -2600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 8192,
            "talk_behaviour": 30026,
            "unk3": "FC 70",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 15,
                "untrigstoryfid": 2047,
                "trigstoryf": "Beat Sandship (Sand Sea layer 3)",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L88"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "54 9F FF F0",
            "unk2": "FF 5F FF FF",
            "posx": -1050.0,
            "posy": -7320.1201171875,
            "posz": 7600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 30027,
            "unk3": "FC 71",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 676,
                "trigstoryf": "-",
                "untrigstoryf": "Talk to Mogma for hint in Waterfall area of Volcano Summit",
                "eventSrc": "300-Mountain.c#L125"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF 0A 10",
            "unk2": "FF DF FF FF",
            "posx": -5730.0,
            "posy": -5590.0,
            "posz": 7500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 20024,
            "talk_behaviour": 30023,
            "unk3": "00 72",
            "name": "NpcStr",
            "extra_info": {
                "trigstoryfid": 1986,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF 5F FF FF",
            "posx": -5460.0,
            "posy": -5590.0,
            "posz": 7440.0,
            "event_flag": 255,
            "transition_type": 206,
            "angle": 50973,
            "talk_behaviour": 30023,
            "unk3": "FC 6D",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F5",
            "unk2": "FF 5F FF FF",
            "posx": -1200.0,
            "posy": -7610.0,
            "posz": 3400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 18204,
            "talk_behaviour": 30024,
            "unk3": "FC 6E",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -4900.0,
            "posy": -5590.0,
            "posz": 6800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 40960,
            "talk_behaviour": 30025,
            "unk3": "FC 6F",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L64"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF 5F FF FF",
            "posx": -5200.0,
            "posy": -6950.0,
            "posz": -2600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 8192,
            "talk_behaviour": 30026,
            "unk3": "FC 70",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L88"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF 0A 10",
            "unk2": "FF DF FF FF",
            "posx": -5730.0,
            "posy": -5590.0,
            "posz": 7500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 20024,
            "talk_behaviour": 30023,
            "unk3": "00 71",
            "name": "NpcStr",
            "extra_info": {
                "trigstoryfid": 1986,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF E0 37 F0",
            "unk2": "FF 5F FF FF",
            "posx": -1050.0,
            "posy": -7320.1201171875,
            "posz": 7600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 30033,
            "unk3": "FC 72",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 13,
                "untrigstoryfid": 2047,
                "trigstoryf": "Beat Fire Sanctuary (Sealed Temple layer 3 / Sealed Grounds layer 3 / Behind The Temple layer 4 / FS Boss Room layer 2 /  FS Entrance layer 4)",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L351"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F2",
            "unk2": "FF 5F FF FF",
            "posx": -5460.0,
            "posy": -5590.0,
            "posz": 7440.0,
            "event_flag": 255,
            "transition_type": 206,
            "angle": 50973,
            "talk_behaviour": 30023,
            "unk3": "FC 6D",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F5",
            "unk2": "FF 5F FF FF",
            "posx": -1200.0,
            "posy": -7610.0,
            "posz": 3400.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 18204,
            "talk_behaviour": 30024,
            "unk3": "FC 6E",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF 5F FF FF",
            "posx": -4900.0,
            "posy": -5590.0,
            "posz": 6800.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 40960,
            "talk_behaviour": 30025,
            "unk3": "FC 6F",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L64"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F1",
            "unk2": "FF 5F FF FF",
            "posx": -5200.0,
            "posy": -6950.0,
            "posz": -2600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 8192,
            "talk_behaviour": 30026,
            "unk3": "FC 70",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L88"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F0",
            "unk2": "FF 5F FF FF",
            "posx": -1050.0,
            "posy": -7320.1201171875,
            "posz": 7600.0,
            "event_flag": 255,
            "transition_type": 255,
            "angle": 32768,
            "talk_behaviour": 30033,
            "unk3": "FC 71",
            "name": "NpcMoN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L351"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF FF F3",
            "unk2": "FF DF FF FF",
            "posx": -300.0,
            "posy": -7860.0,
            "posz": 6000.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 36409,
            "talk_behaviour": 30342,
            "unk3": "FC 72",
            "name": "NpcMoEN",
            "extra_info": {
                "trigstoryfid": 2047,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "303-MountainF2.c#L548"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        },
        {
            "unk1": "FF FF 0A 10",
            "unk2": "FF DF FF FF",
            "posx": -5730.0,
            "posy": -5590.0,
            "posz": 7500.0,
            "event_flag": 0,
            "transition_type": 0,
            "angle": 20024,
            "talk_behaviour": 30023,
            "unk3": "00 73",
            "name": "NpcStr",
            "extra_info": {
                "trigstoryfid": 1986,
                "untrigstoryfid": 2047,
                "trigstoryf": "-",
                "untrigstoryf": "-",
                "eventSrc": "300-Mountain.c#L589"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4,
            "stageid": "F210"
        }
    ]
});