/* eslint-disable */export default Object.freeze({
    "stageid": "F300_5",
    "stagename": "Lanayru Desert: Temple of Time",
    "maxx": 50.0,
    "minx": -500.0,
    "maxz": 1300.0,
    "minz": 0,
    "usedLayers": [
        0
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -12,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "StgBgTs",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 15,
            "byte4": 0,
            "unk1": "FF 5F FF FF",
            "posx": -500.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "FC 00",
            "name": "trolley",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -32,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 67,
            "unk1": "FF FF FF FF",
            "posx": 50.0,
            "posy": 0.0,
            "posz": 1300.0,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "SldDoor",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        }
    ]
});