/* eslint-disable */export default Object.freeze({
    "stageid": "F300_2",
    "stagename": "Lanayru Desert: Lanayru Mine",
    "maxx": 12818.0,
    "minx": -1402.0223388671875,
    "maxz": 1473.3043212890625,
    "minz": -7606.9150390625,
    "usedLayers": [
        "l0"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 97,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": -210.0,
            "posz": -7600.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 01",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "sandflr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": 61,
            "unk1": "FF FF FF FF",
            "posx": 700.0,
            "posy": -210.0,
            "posz": -5200.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "swsyako",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 4,
            "byte4": 61,
            "unk1": "FF FF FF FF",
            "posx": -4.977827072143555,
            "posy": -210.0,
            "posz": -5140.8583984375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "syashtr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 47,
            "byte4": -14,
            "unk1": "13 FF FF FF",
            "posx": 1305.072509765625,
            "posy": 210.0,
            "posz": -4959.033203125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Soil",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 47,
            "byte4": -14,
            "unk1": "04 FF FF FF",
            "posx": 905.3933715820312,
            "posy": 210.0,
            "posz": -4101.89013671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Soil",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 91,
            "tosky_scen_link": -97,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": 313.3341979980469,
            "posy": -210.0,
            "posz": -7603.1513671875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "F1 C8",
            "talk_behaviour": -25511,
            "unk3": "FC 0A",
            "name": "NpcDrb",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 0,
            "tosky_scen_link": 4,
            "scen_link": -3,
            "byte4": 30,
            "unk1": "FF 7F FF FF",
            "posx": 12818.0,
            "posy": 530.0,
            "posz": -3798.0,
            "event_flag": -15,
            "transition_type": 100,
            "unk2": "95 56",
            "talk_behaviour": 0,
            "unk3": "08 0B",
            "name": "SwBnk",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": -1398.8560791015625,
            "posy": 649.530029296875,
            "posz": 744.8245849609375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0D FF FF FF",
            "posx": -1402.0223388671875,
            "posy": 450.0,
            "posz": 1473.3043212890625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "07 FF FF FF",
            "posx": -1400.994140625,
            "posy": 450.0,
            "posz": 1305.1328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "07 FF FF FF",
            "posx": -1398.8563232421875,
            "posy": 649.530029296875,
            "posz": 953.5018920898438,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0D FF FF FF",
            "posx": 1415.080078125,
            "posy": 450.0,
            "posz": 1464.73046875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "07 FF FF FF",
            "posx": 1406.269287109375,
            "posy": 450.0,
            "posz": 1305.32421875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0B FF FF FF",
            "posx": 1410.9658203125,
            "posy": 649.530029296875,
            "posz": 1067.6640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "08 FF FF FF",
            "posx": -550.3101806640625,
            "posy": -210.0,
            "posz": -7399.6630859375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "08 FF FF FF",
            "posx": -548.6589965820312,
            "posy": -210.0,
            "posz": -7594.9931640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "0D FF FF FF",
            "posx": 554.9608154296875,
            "posy": -210.0,
            "posz": -7545.2939453125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "08 FF FF FF",
            "posx": 555.88232421875,
            "posy": -210.0,
            "posz": -7049.060546875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "Barrel",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 47,
            "byte4": -14,
            "unk1": "04 FF FF FF",
            "posx": -825.808837890625,
            "posy": 240.0,
            "posz": -2716.809814453125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "Soil",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 634.4268188476562,
            "posy": 255.0,
            "posz": -6650.388671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 1B",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -16,
            "scen_link": -16,
            "byte4": 64,
            "unk1": "04 FF FF FF",
            "posx": 7.592295169830322,
            "posy": 230.0,
            "posz": -1482.215087890625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "04 1C",
            "name": "ESyako",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -16,
            "scen_link": -16,
            "byte4": 64,
            "unk1": "04 FF FF FF",
            "posx": -2.2177159786224365,
            "posy": 240.0,
            "posz": -4591.69677734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "04 1D",
            "name": "ESyako",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -38,
            "byte4": 15,
            "unk1": "04 DF FF FF",
            "posx": -1248.0733642578125,
            "posy": 240.0,
            "posz": -1001.8189697265625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": -1,
            "unk3": "04 1E",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -38,
            "byte4": 15,
            "unk1": "04 DF FF FF",
            "posx": 1277.0145263671875,
            "posy": 230.0,
            "posz": -3597.3994140625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "04 1F",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -38,
            "byte4": 15,
            "unk1": "04 DF FF FF",
            "posx": 703.7686767578125,
            "posy": 230.0,
            "posz": -4522.8115234375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": -1,
            "unk3": "04 20",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -38,
            "byte4": 15,
            "unk1": "04 DF FF FF",
            "posx": -796.982177734375,
            "posy": 240.0,
            "posz": -3166.613037109375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": -1,
            "unk3": "04 21",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -254.9912872314453,
            "posy": -210.0,
            "posz": -7606.9150390625,
            "event_flag": 107,
            "transition_type": 106,
            "unk2": "FF FF",
            "talk_behaviour": -25459,
            "unk3": "FC 23",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": 711.6881103515625,
            "posy": -210.0,
            "posz": -5397.35595703125,
            "event_flag": 56,
            "transition_type": -1,
            "unk2": "FF 00",
            "talk_behaviour": -25458,
            "unk3": "FC 24",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -32,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 8,
            "byte4": -1,
            "unk1": "07 7F FF FF",
            "posx": 1295.24462890625,
            "posy": 240.0,
            "posz": -3011.172607421875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 8,
            "byte4": -1,
            "unk1": "13 7F FF FF",
            "posx": -1259.474853515625,
            "posy": 240.0,
            "posz": -4959.97509765625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 5,
            "scen_link": 8,
            "byte4": 60,
            "unk1": "FF 7F FF FF",
            "posx": 50.402488708496094,
            "posy": 240.0,
            "posz": -3141.750244140625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": 60,
                "areaflag": "scene flag: 0x6 10"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -1274.97265625,
            "posy": -210.0,
            "posz": -902.8575439453125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -27132,
            "unk3": "FC 13",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -1233.659423828125,
            "posy": -210.0,
            "posz": -3150.990478515625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -26621,
            "unk3": "FC 18",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -642.8013916015625,
            "posy": 245.0,
            "posz": -6648.92333984375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -26048,
            "unk3": "FC 1A",
            "name": "TBox",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 8,
            "byte4": -1,
            "unk1": "07 7F FF FF",
            "posx": 1293.0970458984375,
            "posy": 240.0,
            "posz": -1790.77197265625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -1250.48095703125,
            "posy": 280.0,
            "posz": -191.65802001953125,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -517.9594116210938,
            "posy": 280.0,
            "posz": -113.04804229736328,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 26",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -11,
            "unk1": "FF FF FF FF",
            "posx": 1248.498291015625,
            "posy": 280.0,
            "posz": 95.96057891845703,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 27",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "04 FF FF FF",
            "posx": 513.4481201171875,
            "posy": 280.0,
            "posz": -332.2326354980469,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 28",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 424.0032043457031,
            "posy": 450.0,
            "posz": 736.9840698242188,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 29",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -11,
            "unk1": "FF FF FF FF",
            "posx": 1130.487060546875,
            "posy": 450.0,
            "posz": 681.0022583007812,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2A",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -1054.36572265625,
            "posy": 450.0,
            "posz": 1084.953369140625,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2B",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -11,
            "unk1": "FF FF FF FF",
            "posx": -440.07550048828125,
            "posy": 450.0,
            "posz": 1308.89501953125,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2C",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 828.1871337890625,
            "posy": 450.0,
            "posz": 1188.6082763671875,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2D",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "04 FF FF FF",
            "posx": -731.0953979492188,
            "posy": 450.0,
            "posz": 725.905517578125,
            "sizex": 3.0,
            "sizey": 1.0,
            "sizez": 3.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 2E",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -120,
            "unk1": "13 7F FF FF",
            "posx": -1.1212120056152344,
            "posy": 10.0,
            "posz": -7499.37451171875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 35",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -120,
                "areaflag": "temp flag: 0x0 01"
            },
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -119,
            "unk1": "13 7F FF FF",
            "posx": 706.814697265625,
            "posy": 73.7646255493164,
            "posz": -5065.70654296875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 36",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -119,
                "areaflag": "temp flag: 0x0 02"
            },
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        }
    ]
});