/* eslint-disable */export default Object.freeze({
    "stageid": "F300_4",
    "stagename": "Lanayru Desert: Power Generator #2",
    "maxx": 10414.08984375,
    "minx": -42253.140625,
    "maxz": 39325.9921875,
    "minz": -15300.0,
    "usedLayers": [
        "l0",
        "l1",
        "l13",
        "l2"
    ],
    "usedRooms": [
        "r00"
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -32483.96875,
            "posy": 50.0,
            "posz": -1131.6923828125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -29067.66796875,
            "posy": 464.6317443847656,
            "posz": -8345.2998046875,
            "event_flag": 7,
            "transition_type": 28,
            "unk2": "07 1C",
            "talk_behaviour": -910,
            "unk3": "FC 07",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -24613.853515625,
            "posy": 849.2830810546875,
            "posz": -3990.29931640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -24329.603515625,
            "posy": 804.6709594726562,
            "posz": -4858.287109375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -25503.841796875,
            "posy": 788.4545288085938,
            "posz": -4953.0380859375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -24643.0390625,
            "posy": 1652.650146484375,
            "posz": -4582.744140625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -24887.6328125,
            "posy": 1728.7960205078125,
            "posz": -4297.873046875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -35400.0,
            "posy": 97.30876159667969,
            "posz": -4350.0,
            "event_flag": 57,
            "transition_type": -1,
            "unk2": "FF 00",
            "talk_behaviour": -25481,
            "unk3": "FC 0D",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "StgBgTs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "StgBgTs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -14,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "StgBgTs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "StgBgTs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -30084.248046875,
            "posy": 50.0,
            "posz": -8467.283203125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "F8 E4",
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "AFlw",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -19278.474609375,
            "posy": 50.0,
            "posz": -2849.921142578125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "AFlw",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -31,
            "scen_link": 35,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -32573.203125,
            "posy": 97.30876159667969,
            "posz": 2276.0048828125,
            "event_flag": 74,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": -25469,
            "unk3": "FC 17",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -32235.8203125,
            "posy": 50.0,
            "posz": -1084.42529296875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "Bombf",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -20892.078125,
            "posy": 50.0,
            "posz": -1715.0126953125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 1D",
            "name": "AFlw",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -27048.20703125,
            "posy": 50.0,
            "posz": -5144.57275390625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 1E",
            "name": "AFlw",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "FF FF FF FF",
            "posx": -19306.033203125,
            "posy": 50.0,
            "posz": -3850.527099609375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 0,
            "unk3": "FC 1F",
            "name": "AFlw",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -9,
            "unk1": "FF FF FF FF",
            "posx": -1505.0,
            "posy": 300.0,
            "posz": 6953.58984375,
            "event_flag": 7,
            "transition_type": 28,
            "unk2": "00 00",
            "talk_behaviour": -910,
            "unk3": "04 5F",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -10,
            "unk1": "FF FF FF FF",
            "posx": 6605.0,
            "posy": 300.0,
            "posz": -11475.7080078125,
            "event_flag": -8,
            "transition_type": -28,
            "unk2": "00 00",
            "talk_behaviour": 910,
            "unk3": "FC 60",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -26,
            "unk1": "FF FF FF FF",
            "posx": -10222.0,
            "posy": 300.0,
            "posz": 12092.728515625,
            "event_flag": 3,
            "transition_type": -114,
            "unk2": "F8 E4",
            "talk_behaviour": 910,
            "unk3": "FC 61",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -21,
            "unk1": "FF FF FF FF",
            "posx": 10414.08984375,
            "posy": 300.0,
            "posz": 39325.9921875,
            "event_flag": -8,
            "transition_type": -28,
            "unk2": "15 55",
            "talk_behaviour": -910,
            "unk3": "FC 62",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": -9352.90625,
            "posy": 585.40673828125,
            "posz": 1335.577880859375,
            "event_flag": 32,
            "transition_type": 0,
            "unk2": "20 00",
            "talk_behaviour": 5461,
            "unk3": "FC 63",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -18,
            "unk1": "FF FF FF FF",
            "posx": -9361.3359375,
            "posy": 584.4425048828125,
            "posz": 1368.003662109375,
            "event_flag": 21,
            "transition_type": 85,
            "unk2": "20 00",
            "talk_behaviour": 2730,
            "unk3": "FC 64",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -13,
            "unk1": "FF FF FF FF",
            "posx": -9378.84375,
            "posy": 582.8346557617188,
            "posz": 1384.173583984375,
            "event_flag": 21,
            "transition_type": 85,
            "unk2": "20 00",
            "talk_behaviour": 2730,
            "unk3": "FC 65",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -17,
            "unk1": "FF FF FF FF",
            "posx": -9344.234375,
            "posy": 586.0130004882812,
            "posz": 1378.171630859375,
            "event_flag": 18,
            "transition_type": 125,
            "unk2": "EC CD",
            "talk_behaviour": 2912,
            "unk3": "FC 66",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -68,
            "scen_link": 96,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 2,
            "scen_link": 1,
            "byte4": 77,
            "unk1": "FF 5F FF 15",
            "posx": -23334.0,
            "posy": 50.0,
            "posz": 749.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -1,
            "unk3": "FC 01",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 77,
                "areaflag": "scene flag: 0x8 20"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -66,
            "tosky_scen_link": 60,
            "scen_link": 96,
            "byte4": 16,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -66,
            "scen_link": 96,
            "byte4": 32,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -68,
            "scen_link": -32,
            "byte4": 48,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -67,
            "scen_link": 96,
            "byte4": 64,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -67,
            "tosky_scen_link": -67,
            "scen_link": 96,
            "byte4": 80,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -67,
            "scen_link": -32,
            "byte4": 96,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "ObjBg",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 2,
            "scen_link": 1,
            "byte4": 78,
            "unk1": "FF 5F FF 16",
            "posx": -34352.0,
            "posy": 50.0,
            "posz": -4031.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "FC 14",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 78,
                "areaflag": "scene flag: 0x8 40"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 6,
            "scen_link": 1,
            "byte4": 66,
            "unk1": "FF 5F FF 10",
            "posx": 1680.0,
            "posy": 1984.0,
            "posz": 18933.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -1,
            "unk3": "FC 19",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 66,
                "areaflag": "scene flag: 0x9 04"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 6,
            "scen_link": 1,
            "byte4": 67,
            "unk1": "FF 5F FF 13",
            "posx": -2054.0,
            "posy": 475.0,
            "posz": -6773.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "CE 39",
            "talk_behaviour": -1,
            "unk3": "FC 1A",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 67,
                "areaflag": "scene flag: 0x9 08"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 6,
            "scen_link": 1,
            "byte4": 51,
            "unk1": "FF 5F FF 12",
            "posx": -14960.0,
            "posy": 80.0,
            "posz": 8300.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "5C 71",
            "talk_behaviour": -1,
            "unk3": "FC 1B",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 51,
                "areaflag": "scene flag: 0x7 08"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 3,
            "tosky_scen_link": 6,
            "scen_link": 1,
            "byte4": 2,
            "unk1": "FF 5F FF 14",
            "posx": 9300.0,
            "posy": 247.65599060058594,
            "posz": 10200.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -1,
            "unk3": "FC 1C",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 2,
                "areaflag": "scene flag: 0x1 04"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -16,
            "scen_link": -1,
            "byte4": -117,
            "unk1": "13 7F FF FF",
            "posx": -39379.6015625,
            "posy": 369.1136169433594,
            "posz": -5283.33447265625,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "20 00",
            "talk_behaviour": 0,
            "unk3": "FC 49",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -117,
                "areaflag": "temp flag: 0x0 08"
            },
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -16,
            "scen_link": -1,
            "byte4": -116,
            "unk1": "13 7F FF FF",
            "posx": -39373.7109375,
            "posy": 369.1136169433594,
            "posz": -4236.92529296875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "60 00",
            "talk_behaviour": 0,
            "unk3": "FC 4A",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -116,
                "areaflag": "temp flag: 0x0 10"
            },
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l0"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -15,
            "scen_link": 15,
            "byte4": 49,
            "unk1": "FF FF FF FF",
            "posx": -25736.21875,
            "posy": 42.5,
            "posz": -4589.6005859375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 85",
            "name": "FShutte",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -5,
            "byte4": -16,
            "unk1": "FF DF FF FF",
            "posx": -24923.017578125,
            "posy": 249.5,
            "posz": -4134.91259765625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 5887,
            "unk3": "FC 86",
            "name": "Swhit",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 79,
            "unk1": "FF DF FF FF",
            "posx": -33249.828125,
            "posy": 50.0,
            "posz": -7495.341796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 4111,
            "unk3": "FC 87",
            "name": "HrpHint",
            "extraInfo": {
                "flagid": 79,
                "areaflag": "scene flag: 0x8 80"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -33299.72265625,
            "posy": 50.0,
            "posz": -5003.962890625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "D5 56",
            "talk_behaviour": -25519,
            "unk3": "FC 8A",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF 03",
            "posx": -31501.541015625,
            "posy": 50.0,
            "posz": -8098.34765625,
            "event_flag": 4,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -25517,
            "unk3": "FC 8B",
            "name": "NpcDrb",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF 1F FF FF",
            "posx": -31400.9921875,
            "posy": 50.0,
            "posz": -8097.91748046875,
            "event_flag": 53,
            "transition_type": 123,
            "unk2": "FF 01",
            "talk_behaviour": -25516,
            "unk3": "FC 8C",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 63,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -40281.54296875,
            "posy": 50.0,
            "posz": -4749.73583984375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 8D",
            "name": "TDoorB",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 8E",
            "name": "DstDbrs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -2,
            "byte4": -92,
            "unk1": "07 FF FF FF",
            "posx": -24926.533203125,
            "posy": 572.4600219726562,
            "posz": -4589.166015625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 8F",
            "name": "Ehb",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -2,
            "byte4": -16,
            "unk1": "07 FF FF FF",
            "posx": -20912.76953125,
            "posy": 61.184043884277344,
            "posz": 140.02737426757812,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 90",
            "name": "Ehb",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -3,
            "unk1": "01 FF FF FF",
            "posx": -23198.974609375,
            "posy": 50.0,
            "posz": -8457.4052734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 91",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -3,
            "unk1": "26 FF FF FF",
            "posx": -21602.97265625,
            "posy": 50.0,
            "posz": -8002.15283203125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 92",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "01 FF FF FF",
            "posx": -30551.763671875,
            "posy": 50.0,
            "posz": -3851.751220703125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 93",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "26 FF FF FF",
            "posx": -32651.33203125,
            "posy": 50.0,
            "posz": -2794.44091796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "01 FF FF FF",
            "posx": -30292.861328125,
            "posy": 50.0,
            "posz": -1591.14013671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 95",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -21167.830078125,
            "posy": 50.0,
            "posz": -1493.9073486328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -164,
            "unk3": "FC 96",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -31396.568359375,
            "posy": 50.0,
            "posz": -7525.62744140625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": -163,
            "unk3": "FC 97",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -32187.103515625,
            "posy": 50.0,
            "posz": -8283.6142578125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "20 00",
            "talk_behaviour": -162,
            "unk3": "FC 98",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -19218.9296875,
            "posy": 50.0,
            "posz": -3457.38330078125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -161,
            "unk3": "FC 99",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -30942.03515625,
            "posy": 570.0,
            "posz": -7519.8447265625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9A",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "26 FF FF FF",
            "posx": -30737.123046875,
            "posy": 570.0,
            "posz": -7484.22900390625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9B",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -32264.876953125,
            "posy": 650.0,
            "posz": -6796.591796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9C",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "13 FF FF FF",
            "posx": -28129.388671875,
            "posy": -229.5369415283203,
            "posz": -225.11624145507812,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9D",
            "name": "OcGrs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "14 FF FF FF",
            "posx": -26657.283203125,
            "posy": -435.05010986328125,
            "posz": 19.591018676757812,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9E",
            "name": "OcGrs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 97,
            "unk1": "FF FF FF FF",
            "posx": 100.0,
            "posy": -170.0,
            "posz": -15300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9F",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 82,
            "unk1": "FF FF FF FF",
            "posx": 10025.0,
            "posy": 200.0,
            "posz": 5700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A0",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 64,
            "unk1": "FF FF FF FF",
            "posx": -9445.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A1",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 30,
            "unk1": "FF 7F FF FF",
            "posx": -2200.0,
            "posy": 550.0,
            "posz": -3800.0,
            "event_flag": -15,
            "transition_type": 100,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A2",
            "name": "SwBnk",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -30,
            "scen_link": 7,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -31107.462890625,
            "posy": 50.0,
            "posz": -8137.94384765625,
            "event_flag": 88,
            "transition_type": -1,
            "unk2": "FF 01",
            "talk_behaviour": -25457,
            "unk3": "FC A3",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -15,
            "scen_link": 71,
            "byte4": 30,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A4",
            "name": "D300Obj",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 3,
            "unk1": "FF 5F FF FF",
            "posx": -22395.0,
            "posy": 50.0,
            "posz": -4589.873046875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "FC 81",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 1,
            "unk1": "FF 5F FF FF",
            "posx": -19987.775390625,
            "posy": 60.0,
            "posz": -6371.01025390625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -1,
            "unk3": "FC 82",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 0,
            "unk1": "FF 5F FF FF",
            "posx": -31649.076171875,
            "posy": 60.0,
            "posz": -8099.3857421875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -1,
            "unk3": "FC 83",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 2,
            "unk1": "FF 5F FF FF",
            "posx": -22290.0,
            "posy": 50.0,
            "posz": -1430.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -1,
            "unk3": "FC 84",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 19,
            "scen_link": 8,
            "byte4": 58,
            "unk1": "FF 7F FF FF",
            "posx": -31677.767578125,
            "posy": 700.0,
            "posz": -7536.02783203125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 88",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": 58,
                "areaflag": "scene flag: 0x6 04"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 8,
            "byte4": 59,
            "unk1": "13 7F FF FF",
            "posx": -31385.189453125,
            "posy": 790.0,
            "posz": -6775.30615234375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 89",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": 59,
                "areaflag": "scene flag: 0x6 08"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "0D FF FF FF",
            "posx": -31074.70703125,
            "posy": 50.0,
            "posz": -1844.505126953125,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A5",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -2,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "06 FF FF FF",
            "posx": -31553.80859375,
            "posy": 50.0,
            "posz": -5844.984375,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A6",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "0D FF FF FF",
            "posx": -22044.654296875,
            "posy": 50.0,
            "posz": 1250.3543701171875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A7",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -24794.763671875,
            "posy": 50.0,
            "posz": -7819.63330078125,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A8",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "04 FF FF FF",
            "posx": -22302.525390625,
            "posy": 50.0,
            "posz": -8150.1494140625,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A9",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -28524.060546875,
            "posy": 50.0,
            "posz": -4950.51025390625,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AA",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -2,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -22096.703125,
            "posy": 50.0,
            "posz": -4865.115234375,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AB",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l1"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 1,
            "unk1": "FF FF FF FF",
            "posx": -34448.78125,
            "posy": 50.0,
            "posz": -1305.395263671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 81",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -30939.564453125,
            "posy": 570.0,
            "posz": -7519.8447265625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 83",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "05 FF FF FF",
            "posx": -30734.65234375,
            "posy": 570.0,
            "posz": -7484.22900390625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 84",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 17,
            "tosky_scen_link": -97,
            "scen_link": -4,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -33299.1015625,
            "posy": 50.0,
            "posz": -4999.34521484375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "D5 56",
            "talk_behaviour": -25519,
            "unk3": "FC 85",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 127,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -40300.0,
            "posy": 189.1800079345703,
            "posz": -4750.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 86",
            "name": "TDoorB",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -31398.484375,
            "posy": 50.0,
            "posz": -8401.740234375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -25517,
            "unk3": "FC 87",
            "name": "NpcDrb",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 79,
            "unk1": "FF DF FF FF",
            "posx": -33249.0,
            "posy": 50.0,
            "posz": -7495.34130859375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 4111,
            "unk3": "FC 88",
            "name": "HrpHint",
            "extraInfo": {
                "flagid": 79,
                "areaflag": "scene flag: 0x8 80"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -5,
            "byte4": -16,
            "unk1": "FF DF FF FF",
            "posx": -24923.017578125,
            "posy": 249.5,
            "posz": -4134.91259765625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 5887,
            "unk3": "FC 8A",
            "name": "Swhit",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -15,
            "scen_link": 15,
            "byte4": 49,
            "unk1": "FF FF FF FF",
            "posx": -25736.0,
            "posy": 41.29999923706055,
            "posz": -4590.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 8B",
            "name": "FShutte",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "13 FF FF FF",
            "posx": -28129.57421875,
            "posy": -229.24160766601562,
            "posz": -224.931884765625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 8F",
            "name": "OcGrs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "14 FF FF FF",
            "posx": -26653.390625,
            "posy": -435.05010986328125,
            "posz": 15.697930335998535,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 90",
            "name": "OcGrs",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 97,
            "unk1": "FF FF FF FF",
            "posx": 100.0,
            "posy": -170.0,
            "posz": -15300.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 91",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 82,
            "unk1": "FF FF FF FF",
            "posx": 10025.0,
            "posy": 200.0,
            "posz": 5700.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 92",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -10,
            "byte4": 64,
            "unk1": "FF FF FF FF",
            "posx": -9445.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 93",
            "name": "SwBnkS",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 30,
            "unk1": "FF 7F FF FF",
            "posx": -2200.0,
            "posy": 550.0,
            "posz": -3800.0,
            "event_flag": -15,
            "transition_type": 100,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "SwBnk",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -3,
            "unk1": "01 FF FF FF",
            "posx": -23198.97265625,
            "posy": 50.0,
            "posz": -8457.4052734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 95",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -3,
            "unk1": "26 FF FF FF",
            "posx": -21602.96875,
            "posy": 50.0,
            "posz": -7999.98388671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "80 00",
            "talk_behaviour": 0,
            "unk3": "FC 96",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "01 FF FF FF",
            "posx": -30551.76171875,
            "posy": 50.0,
            "posz": -3851.751220703125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 97",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "26 FF FF FF",
            "posx": -32651.330078125,
            "posy": 50.0,
            "posz": -2794.44091796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 98",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 5,
            "byte4": 61,
            "unk1": "01 FF FF FF",
            "posx": -30292.859375,
            "posy": 50.0,
            "posz": -1591.14013671875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 99",
            "name": "EOr",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -15,
            "scen_link": 71,
            "byte4": 30,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 9A",
            "name": "D300Obj",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 3,
            "unk1": "FF FF FF FF",
            "posx": -40319.95703125,
            "posy": 682.8500366210938,
            "posz": -6162.1640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 9B",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 1,
            "unk1": "FF FF FF FF",
            "posx": -42253.140625,
            "posy": 50.0,
            "posz": -4252.96826171875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 9C",
            "name": "AncJwls",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 3,
            "unk1": "FF FF FF FF",
            "posx": -41499.44921875,
            "posy": 682.8500366210938,
            "posz": -3960.33642578125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 9D",
            "name": "Item",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -19218.9296875,
            "posy": 50.0,
            "posz": -3457.383056640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -161,
            "unk3": "FC 9E",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": 15,
            "unk1": "21 DF FF FF",
            "posx": -21164.763671875,
            "posy": 50.0,
            "posz": -1493.9073486328125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": -164,
            "unk3": "FC 9F",
            "name": "EBce",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -32262.40625,
            "posy": 650.0,
            "posz": -6796.591796875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A0",
            "name": "Tubo",
            "extraInfo": {
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 62,
            "unk1": "14 DF FF FF",
            "posx": -31399.919921875,
            "posy": 770.0,
            "posz": -6771.318359375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": -3,
            "unk3": "FC A1",
            "name": "EGerock",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": 82,
            "unk1": "14 DF FF FF",
            "posx": -23584.59765625,
            "posy": 916.0,
            "posz": -5657.77099609375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": -3,
            "unk3": "FC A2",
            "name": "EGerock",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 1,
            "unk1": "FF 5F FF FF",
            "posx": -19987.0,
            "posy": 60.0,
            "posz": -6371.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -1,
            "unk3": "FC 82",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": 19,
            "scen_link": 8,
            "byte4": 58,
            "unk1": "FF 7F FF FF",
            "posx": -31677.767578125,
            "posy": 700.0,
            "posz": -7538.14306640625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 89",
            "name": "BlsRock",
            "extraInfo": {
                "flagid": 58,
                "areaflag": "scene flag: 0x6 04"
            },
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 2,
            "unk1": "FF 5F FF FF",
            "posx": -22290.0,
            "posy": 50.0,
            "posz": -1430.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -1,
            "unk3": "FC 8C",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 0,
            "unk1": "FF 5F FF FF",
            "posx": -31648.787109375,
            "posy": 60.0,
            "posz": -8099.5537109375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": -1,
            "unk3": "FC 8D",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": 20,
            "byte4": 3,
            "unk1": "FF 5F FF FF",
            "posx": -22395.0,
            "posy": 50.0,
            "posz": -4590.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "FC 8E",
            "name": "trolley",
            "type": "OBJS",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "0D FF FF FF",
            "posx": -31071.662109375,
            "posy": 50.0,
            "posz": -1843.6962890625,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A3",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -2,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "06 FF FF FF",
            "posx": -31553.216796875,
            "posy": 50.0,
            "posz": -5845.234375,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A4",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "0D FF FF FF",
            "posx": -22044.654296875,
            "posy": 50.0,
            "posz": 1249.587646484375,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A5",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -24794.849609375,
            "posy": 50.0,
            "posz": -7819.77294921875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A6",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "04 FF FF FF",
            "posx": -22305.462890625,
            "posy": 50.0,
            "posz": -8150.14892578125,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A7",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -28522.14453125,
            "posy": 50.0,
            "posz": -4950.19091796875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A8",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -2,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -22095.6171875,
            "posy": 50.0,
            "posz": -4864.02880859375,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC A9",
            "name": "ECactus",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "26 FF FF FF",
            "posx": -39763.92578125,
            "posy": 50.0,
            "posz": -7057.46240234375,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AA",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -41823.0,
            "posy": 50.0,
            "posz": -7045.0,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AB",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "26 FF FF FF",
            "posx": -42240.07421875,
            "posy": 50.0,
            "posz": -6849.24169921875,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AC",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -42248.58203125,
            "posy": 50.0,
            "posz": -4251.8623046875,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AD",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -41940.0,
            "posy": 50.0,
            "posz": -2445.0,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AE",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -34448.21875,
            "posy": 50.0,
            "posz": -1313.474609375,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC AF",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "26 FF FF FF",
            "posx": -34823.78515625,
            "posy": 50.0,
            "posz": -1520.72509765625,
            "sizex": 2.0,
            "sizey": 1.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC B0",
            "name": "vmSand",
            "type": "SOBJ",
            "roomid": "r00",
            "layerid": "l2"
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -8,
            "byte4": -45,
            "unk1": "FF FF FF FF",
            "posx": -40280.0,
            "posy": 50.0,
            "posz": -4750.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 81",
            "name": "TDoor",
            "type": "OBJ ",
            "roomid": "r00",
            "layerid": "l13"
        }
    ]
});