/* eslint-disable */export default Object.freeze({
    "stageid": "F301_5",
    "stagename": "Lanayru Desert: Skipper's Retreat Shack",
    "maxx": 965.0,
    "minx": -1224.52978515625,
    "maxz": 920.978271484375,
    "minz": -995.0,
    "usedLayers": [
        0
    ],
    "usedRooms": [
        0
    ],
    "allObjects": [
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -624.47705078125,
            "posy": 0.0,
            "posz": -767.1420288085938,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 03",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -680.05224609375,
            "posy": 0.0,
            "posz": -695.8920288085938,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 04",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -791.35400390625,
            "posy": 0.0,
            "posz": 455.3884582519531,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 05",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -753.95556640625,
            "posy": 0.0,
            "posz": 551.8997192382812,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 06",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -222.32945251464844,
            "posy": 0.0,
            "posz": -734.984619140625,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 07",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -404.7090759277344,
            "posy": 0.0,
            "posz": -727.8519897460938,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 08",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -323.8429870605469,
            "posy": 0.0,
            "posz": -782.6246948242188,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 09",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -231.76382446289062,
            "posy": 0.0,
            "posz": 736.3317260742188,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0A",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 534.9840087890625,
            "posy": 0.0,
            "posz": -639.5970458984375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0B",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "14 FF FF FF",
            "posx": -100.0,
            "posy": 0.0,
            "posz": -995.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0C",
            "name": "chest",
            "angle": -13300,
            "extraInfo": {
                "first_4_bytes": "0F FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -1,
            "unk1": "07 FF FF FF",
            "posx": 386.79510498046875,
            "posy": 0.0,
            "posz": 659.661376953125,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0D",
            "name": "EKg",
            "angle": -31859,
            "extraInfo": {
                "first_4_bytes": "FF FF F9 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -1,
            "unk1": "07 FF FF FF",
            "posx": 654.0806274414062,
            "posy": 0.0,
            "posz": 556.2528076171875,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0E",
            "name": "EKg",
            "angle": 29340,
            "extraInfo": {
                "first_4_bytes": "FF FF F9 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -7,
            "byte4": -1,
            "unk1": "07 FF FF FF",
            "posx": 553.5950317382812,
            "posy": 0.0,
            "posz": 769.1229858398438,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 0F",
            "name": "EKg",
            "angle": 19103,
            "extraInfo": {
                "first_4_bytes": "FF FF F9 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -838.7958984375,
            "posy": 0.0,
            "posz": -32.39107894897461,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 10",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -326.16339111328125,
            "posy": 0.0,
            "posz": 790.8756713867188,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 11",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -406.23675537109375,
            "posy": 0.0,
            "posz": 726.8391723632812,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 12",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": 619.9586791992188,
            "posy": 0.0,
            "posz": -664.6552734375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 13",
            "name": "AncJwls",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F1"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": 73.3126220703125,
            "posy": 3.014859914779663,
            "posz": 920.978271484375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 14",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": -675.5653076171875,
            "posy": 0.0,
            "posz": 618.4124755859375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 15",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": 325.7060546875,
            "posy": 10.696125984191895,
            "posz": -788.1019287109375,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 16",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": 423.83697509765625,
            "posy": 2.374829053878784,
            "posz": -763.4293823242188,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 17",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -33,
            "byte4": -15,
            "unk1": "07 FF FF FF",
            "posx": 221.22439575195312,
            "posy": 16.646141052246094,
            "posz": -814.664794921875,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 18",
            "name": "Tubo",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF DF F1",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -674.1321411132812,
            "posy": 0.0,
            "posz": -571.9629516601562,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 19",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": 15,
            "scen_link": -2,
            "byte4": 2,
            "unk1": "FF FF FF FF",
            "posx": -752.35693359375,
            "posy": 0.0,
            "posz": -526.4478149414062,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1A",
            "name": "Item",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF 0F FE 02",
                "flagid": -1,
                "areaflag": "no flag set"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 2,
            "unk1": "FF 1F FF FF",
            "posx": -1224.52978515625,
            "posy": 82.36534881591797,
            "posz": -529.8048706054688,
            "event_flag": 16,
            "transition_type": 17,
            "talk_behaviour": -25295,
            "unk3": "FC 1B",
            "name": "NpcTke",
            "angle": -1,
            "extraInfo": {
                "first_4_bytes": "FF FF FF 02"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -4,
            "byte4": -91,
            "unk1": "FF FF FF FF",
            "posx": 0.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 1C",
            "name": "Char",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FC A5"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 100,
            "byte4": -1,
            "unk1": "FF DF FA E2",
            "posx": 195.56858825683594,
            "posy": 335.74334716796875,
            "posz": 15.548521041870117,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": -25292,
            "unk3": "FC 1D",
            "name": "NpcStr",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF 64 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 92,
            "tosky_scen_link": 127,
            "scen_link": 100,
            "byte4": -1,
            "unk1": "FF DF FA E4",
            "posx": 174.83721923828125,
            "posy": 335.74334716796875,
            "posz": 15.548521041870117,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": -25291,
            "unk3": "FC 1E",
            "name": "NpcStr",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "5C 7F 64 FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -608.767333984375,
            "posy": 0.0,
            "posz": -330.7855224609375,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -25311,
            "unk3": "FC 1F",
            "name": "NpcDrb",
            "angle": 21781,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF 5F FF FF",
            "posx": -608.7673950195312,
            "posy": 0.0,
            "posz": -34.39023971557617,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": -25311,
            "unk3": "FC 20",
            "name": "NpcDrb",
            "angle": 7271,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 0,
            "byte4": 5,
            "unk1": "FF 5F FF FF",
            "posx": 965.0,
            "posy": 0.0,
            "posz": 0.0,
            "event_flag": -1,
            "transition_type": 0,
            "talk_behaviour": -16,
            "unk3": "FC 00",
            "name": "Door",
            "angle": 64,
            "extraInfo": {
                "first_4_bytes": "00 00 00 05"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": 443.1773681640625,
            "posy": 0.0,
            "posz": 557.969970703125,
            "event_flag": -3,
            "transition_type": 17,
            "talk_behaviour": -32158,
            "unk3": "FC 01",
            "name": "TBox",
            "angle": 22197,
            "extraInfo": {
                "first_4_bytes": "FF FF FF F3"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -17,
            "unk1": "FF FF FF FF",
            "posx": 4.501613140106201,
            "posy": 0.0,
            "posz": 6.002159118652344,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 02",
            "name": "ODesert",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF EF"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -288.5483093261719,
            "posy": 0.0,
            "posz": 140.19857788085938,
            "sizex": 1.7999999523162842,
            "sizey": 1.5,
            "sizez": 1.7999999523162842,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 21",
            "name": "vmSand",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": 102.70355224609375,
            "posy": 0.0,
            "posz": -224.96983337402344,
            "sizex": 2.0,
            "sizey": 2.0,
            "sizez": 2.0,
            "event_flag": 0,
            "transition_type": 0,
            "talk_behaviour": 0,
            "unk3": "FC 22",
            "name": "vmSand",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "FF FF FF FF"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 47,
            "tosky_scen_link": -16,
            "scen_link": -1,
            "byte4": -88,
            "unk1": "13 7F FF FF",
            "posx": 134.05111694335938,
            "posy": 843.432861328125,
            "posz": -430.70166015625,
            "sizex": 1.2000000476837158,
            "sizey": 2.0,
            "sizez": 1.2000000476837158,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 23",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "2F F0 FF A8",
                "flagid": -88,
                "areaflag": "temp flag: 0x4 01"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 47,
            "tosky_scen_link": -16,
            "scen_link": -1,
            "byte4": -87,
            "unk1": "13 7F FF FF",
            "posx": 433.7572021484375,
            "posy": 843.432861328125,
            "posz": 75.14042663574219,
            "sizex": 1.2000000476837158,
            "sizey": 2.0,
            "sizez": 1.2000000476837158,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 24",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "2F F0 FF A9",
                "flagid": -87,
                "areaflag": "temp flag: 0x4 02"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 47,
            "tosky_scen_link": -16,
            "scen_link": -1,
            "byte4": -86,
            "unk1": "13 7F FF FF",
            "posx": -388.93096923828125,
            "posy": 843.432861328125,
            "posz": 274.82598876953125,
            "sizex": 1.2000000476837158,
            "sizey": 2.0,
            "sizez": 1.2000000476837158,
            "event_flag": -1,
            "transition_type": -1,
            "talk_behaviour": 0,
            "unk3": "FC 25",
            "name": "TgReact",
            "angle": 0,
            "extraInfo": {
                "first_4_bytes": "2F F0 FF AA",
                "flagid": -86,
                "areaflag": "temp flag: 0x4 04"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        }
    ]
});