/* eslint-disable */export default Object.freeze({
    "stageid": "F400",
    "stagename": "Sealed Grounds: Forest",
    "maxx": 1365.0419921875,
    "minx": -20000.0,
    "maxz": 15790.0,
    "minz": 0,
    "usedLayers": [
        0,
        1,
        2,
        3,
        4,
        5,
        6,
        7,
        8,
        13
    ],
    "usedRooms": [
        0,
        1
    ],
    "allObjects": [
        {
            "byte1": -4,
            "tosky_scen_link": 4,
            "scen_link": 0,
            "byte4": 3,
            "unk1": "FF FF FF FF",
            "posx": -13916.8525390625,
            "posy": 7639.60009765625,
            "posz": 9523.4189453125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "4D 82",
            "talk_behaviour": 0,
            "unk3": "FC 2A",
            "name": "Log",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": -32,
            "scen_link": 21,
            "byte4": 49,
            "unk1": "FF 5F FF FF",
            "posx": -6874.7236328125,
            "posy": 7920.0,
            "posz": 9271.7119140625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15185,
            "unk3": "FC 2E",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 16,
            "tosky_scen_link": 98,
            "scen_link": 49,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -10007.78515625,
            "posy": 7500.0,
            "posz": 5640.86962890625,
            "event_flag": 17,
            "transition_type": -1,
            "unk2": "22 D8",
            "talk_behaviour": -15184,
            "unk3": "FC 2F",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": -94,
            "scen_link": 12,
            "byte4": 0,
            "unk1": "FF 5F FF FF",
            "posx": -9684.84375,
            "posy": 7500.0,
            "posz": 7812.5009765625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "17 77",
            "talk_behaviour": -15183,
            "unk3": "FC 30",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -101,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 10500.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15229,
            "unk3": "FC 35",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -97,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 10500.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15228,
            "unk3": "FC 36",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 10500.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15227,
            "unk3": "FC 37",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -89,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 10500.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15226,
            "unk3": "FC 38",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -85,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 10500.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15221,
            "unk3": "FC 39",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -97,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3A",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3B",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -89,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3C",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -85,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3D",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -101,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 10800.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3E",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 10800.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 3F",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -89,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 10800.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 40",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -85,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 10800.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 41",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -101,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 10950.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 42",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -97,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 10950.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 43",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 10950.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 44",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -85,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 10950.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 45",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -101,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 11100.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 46",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -97,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 11100.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 47",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 11100.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 48",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -89,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 11100.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 49",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -101,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -7000.0,
            "posy": 7920.0,
            "posz": 11250.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 4A",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -97,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6900.0,
            "posy": 7920.0,
            "posz": 11250.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 4B",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -89,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6800.0,
            "posy": 7920.0,
            "posz": 11250.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 4C",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -85,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6700.0,
            "posy": 7920.0,
            "posz": 11250.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 4D",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 53,
            "tosky_scen_link": 102,
            "scen_link": -93,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6500.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": 112,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15217,
            "unk3": "FC 4E",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -105,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 10650.0,
            "event_flag": -125,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 53",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -105,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 10800.0,
            "event_flag": -124,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 54",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -105,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 10950.0,
            "event_flag": -123,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 55",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -105,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 11100.0,
            "event_flag": -122,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 56",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 61,
            "tosky_scen_link": 102,
            "scen_link": -105,
            "byte4": 17,
            "unk1": "FF 1F FF FF",
            "posx": -6600.0,
            "posy": 7920.0,
            "posz": 11250.0,
            "event_flag": -117,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15218,
            "unk3": "FC 57",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": 33,
            "scen_link": 31,
            "byte4": -14,
            "unk1": "FF 1F FF FF",
            "posx": -10528.880859375,
            "posy": 7500.0,
            "posz": 5825.6572265625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "FF FF",
            "talk_behaviour": 6006,
            "unk3": "FC 5B",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -16,
            "tosky_scen_link": 0,
            "scen_link": 0,
            "byte4": 72,
            "unk1": "FF DF FF FF",
            "posx": -9373.0,
            "posy": 7500.0,
            "posz": 8235.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "7B 05",
            "talk_behaviour": 4103,
            "unk3": "FC 63",
            "name": "HrpHint",
            "extraInfo": {
                "flagid": 72,
                "areaflag": "scene flag: 0x8 01"
            },
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -7970.1875,
            "posy": 7500.0,
            "posz": 7768.2177734375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 64",
            "name": "CyStone",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -7876.40185546875,
            "posy": 7500.0,
            "posz": 7864.18212890625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 65",
            "name": "CyStone",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -8100.1240234375,
            "posy": 7500.0,
            "posz": 6822.6650390625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 66",
            "name": "CyStone",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -16,
            "unk1": "FF FF FF FF",
            "posx": -8119.6416015625,
            "posy": 7500.0,
            "posz": 6972.298828125,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 67",
            "name": "CyStone",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 9,
            "unk1": "FF FF FF FF",
            "posx": -6377.0234375,
            "posy": 8219.1904296875,
            "posz": 10438.2978515625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "85 B1",
            "talk_behaviour": 0,
            "unk3": "FC 68",
            "name": "SwrdPrj",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "1E FF FF FF",
            "posx": -11752.140625,
            "posy": 8210.3486328125,
            "posz": 9131.8779296875,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 7E",
            "name": "fruit",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "1E FF FF FF",
            "posx": -9628.052734375,
            "posy": 8559.5390625,
            "posz": 7621.25146484375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 7F",
            "name": "fruit",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -4,
            "unk1": "1E FF FF FF",
            "posx": -9823.6044921875,
            "posy": 8376.4990234375,
            "posz": 5584.12744140625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 80",
            "name": "fruit",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -6,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "D5 56",
            "talk_behaviour": 0,
            "unk3": "FC 81",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -25,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": 14,
            "transition_type": 56,
            "unk2": "C7 1D",
            "talk_behaviour": -1456,
            "unk3": "FC 82",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -20,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -15,
            "transition_type": -56,
            "unk2": "DD DE",
            "talk_behaviour": 910,
            "unk3": "FC 83",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -15,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -2,
            "transition_type": -108,
            "unk2": "CD 28",
            "talk_behaviour": -364,
            "unk3": "FC 84",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -29,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "15 55",
            "talk_behaviour": 0,
            "unk3": "FC 85",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -28,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -8,
            "transition_type": -28,
            "unk2": "0A AA",
            "talk_behaviour": -910,
            "unk3": "FC 86",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -12,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -4,
            "transition_type": 114,
            "unk2": "20 00",
            "talk_behaviour": -910,
            "unk3": "FC 87",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -7,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -4,
            "transition_type": 114,
            "unk2": "EE B9",
            "talk_behaviour": -910,
            "unk3": "FC 88",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": -2,
            "unk1": "FF FF FF FF",
            "posx": -20000.0,
            "posy": 8500.0,
            "posz": 11500.0,
            "event_flag": -4,
            "transition_type": 114,
            "unk2": "EA AB",
            "talk_behaviour": -1820,
            "unk3": "FC 89",
            "name": "GodCube",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 1,
            "tosky_scen_link": 5,
            "scen_link": 1,
            "byte4": 31,
            "unk1": "FF 5F FF 00",
            "posx": -11029.0810546875,
            "posy": 7500.0,
            "posz": 6279.25146484375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "37 77",
            "talk_behaviour": -1,
            "unk3": "FC 2B",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 31,
                "areaflag": "scene flag: 0x2 80"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 1,
            "byte4": 4,
            "unk1": "FF 5F FF FF",
            "posx": -3170.0,
            "posy": 7600.0,
            "posz": 10344.0,
            "event_flag": -1,
            "transition_type": 0,
            "unk2": "40 00",
            "talk_behaviour": 2048,
            "unk3": "FC 2C",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 1,
            "byte4": 4,
            "unk1": "FF 5F FF FF",
            "posx": -3170.0,
            "posy": 7600.0,
            "posz": 10502.0,
            "event_flag": -1,
            "transition_type": 0,
            "unk2": "C0 00",
            "talk_behaviour": 2048,
            "unk3": "FC 2D",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -5600.0,
            "posy": 8000.0,
            "posz": 10000.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -451,
            "unk3": "FC 31",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -5450.0,
            "posy": 8000.0,
            "posz": 10000.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -450,
            "unk3": "FC 32",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -5300.0,
            "posy": 8000.0,
            "posz": 10000.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -449,
            "unk3": "FC 33",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -5150.0,
            "posy": 8000.0,
            "posz": 10000.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -448,
            "unk3": "FC 34",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 0,
            "byte4": 32,
            "unk1": "FF 5F FF FF",
            "posx": 1365.0419921875,
            "posy": 7600.0,
            "posz": 10420.0068359375,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "C0 00",
            "talk_behaviour": -1,
            "unk3": "FC 4F",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 32,
                "areaflag": "scene flag: 0x5 01"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -61,
            "tosky_scen_link": 111,
            "scen_link": 0,
            "byte4": 7,
            "unk1": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 7607.0,
            "posz": 7610.0,
            "event_flag": 13,
            "transition_type": 3,
            "unk2": "80 00",
            "talk_behaviour": 2064,
            "unk3": "FC 50",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 1,
            "byte4": 4,
            "unk1": "FF 5F FF FF",
            "posx": -1760.0,
            "posy": 7600.0,
            "posz": 10341.0,
            "event_flag": 23,
            "transition_type": 1,
            "unk2": "40 00",
            "talk_behaviour": 32,
            "unk3": "FC 51",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 0,
            "tosky_scen_link": 0,
            "scen_link": 1,
            "byte4": 4,
            "unk1": "FF 5F FF FF",
            "posx": -1760.0,
            "posy": 7600.0,
            "posz": 10499.0,
            "event_flag": 23,
            "transition_type": 1,
            "unk2": "C0 00",
            "talk_behaviour": 32,
            "unk3": "FC 52",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 1,
            "tosky_scen_link": 19,
            "scen_link": 1,
            "byte4": 35,
            "unk1": "FF 5F FF 1C",
            "posx": -8043.06689453125,
            "posy": 8403.87890625,
            "posz": 153.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "45 B0",
            "talk_behaviour": -1,
            "unk3": "FC 58",
            "name": "saveObj",
            "extraInfo": {
                "flagid": 35,
                "areaflag": "scene flag: 0x5 08"
            },
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -1235.0,
            "posy": 7700.330078125,
            "posz": 12500.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "80 00",
            "talk_behaviour": -32642,
            "unk3": "FC 59",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -5750.0,
            "posy": 8000.0,
            "posz": 10000.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": -340,
            "unk3": "FC 5A",
            "name": "TBox",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -61,
            "tosky_scen_link": 111,
            "scen_link": 0,
            "byte4": 7,
            "unk1": "FF 5F FF FF",
            "posx": 0.0,
            "posy": 7607.0,
            "posz": 7610.0,
            "event_flag": 13,
            "transition_type": 3,
            "unk2": "80 00",
            "talk_behaviour": 2064,
            "unk3": "FC 69",
            "name": "Door",
            "type": "OBJS",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": -4875.0,
            "posy": 8820.0,
            "posz": 15535.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 6A",
            "name": "Light00",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": -9035.0,
            "posy": 9480.0,
            "posz": 215.0,
            "sizex": 0.5,
            "sizey": 0.5,
            "sizez": 0.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 6B",
            "name": "Light00",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF FF FF FF",
            "posx": -6680.0,
            "posy": 9000.0,
            "posz": 15790.0,
            "sizex": 0.3499999940395355,
            "sizey": 0.3499999940395355,
            "sizez": 35.0,
            "event_flag": 14,
            "transition_type": -18,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 6C",
            "name": "Light00",
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -15,
            "scen_link": 0,
            "byte4": -112,
            "unk1": "04 7F FF FF",
            "posx": -12921.5341796875,
            "posy": 7639.60009765625,
            "posz": 9223.875,
            "sizex": 2.5999999046325684,
            "sizey": 3.0,
            "sizez": 2.5999999046325684,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 8E",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -112,
                "areaflag": "temp flag: 0x3 01"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 15,
            "tosky_scen_link": -15,
            "scen_link": 0,
            "byte4": -111,
            "unk1": "04 7F FF FF",
            "posx": -13649.193359375,
            "posy": 7639.60009765625,
            "posz": 9580.9931640625,
            "sizex": 1.5,
            "sizey": 3.0,
            "sizez": 1.5,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "2C CC",
            "talk_behaviour": 0,
            "unk3": "FC 8F",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -111,
                "areaflag": "temp flag: 0x3 02"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 31,
            "tosky_scen_link": -16,
            "scen_link": 0,
            "byte4": -110,
            "unk1": "12 7F FF FF",
            "posx": -11112.486328125,
            "posy": 8100.0,
            "posz": 8210.9287109375,
            "sizex": 1.0,
            "sizey": 1.399999976158142,
            "sizez": 0.30000001192092896,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "60 B6",
            "talk_behaviour": 0,
            "unk3": "FC 90",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -110,
                "areaflag": "temp flag: 0x3 04"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 31,
            "tosky_scen_link": -16,
            "scen_link": 0,
            "byte4": -109,
            "unk1": "12 7F FF FF",
            "posx": -11171.0390625,
            "posy": 8100.0,
            "posz": 8266.6005859375,
            "sizex": 1.0,
            "sizey": 1.399999976158142,
            "sizez": 0.30000001192092896,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "E0 B7",
            "talk_behaviour": 0,
            "unk3": "FC 91",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -109,
                "areaflag": "temp flag: 0x3 08"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 31,
            "tosky_scen_link": -16,
            "scen_link": 0,
            "byte4": -108,
            "unk1": "12 7F FF FF",
            "posx": -3262.1162109375,
            "posy": 8030.0,
            "posz": 10421.3935546875,
            "sizex": 1.0,
            "sizey": 2.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "40 00",
            "talk_behaviour": 0,
            "unk3": "FC 92",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -108,
                "areaflag": "temp flag: 0x3 10"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": 47,
            "tosky_scen_link": -16,
            "scen_link": 0,
            "byte4": -107,
            "unk1": "12 7F FF FF",
            "posx": -8057.45068359375,
            "posy": 7850.0,
            "posz": 9476.9716796875,
            "sizex": 1.0,
            "sizey": 1.0,
            "sizez": 1.0,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "8E EF",
            "talk_behaviour": 0,
            "unk3": "FC 93",
            "name": "TgReact",
            "extraInfo": {
                "flagid": -107,
                "areaflag": "temp flag: 0x3 20"
            },
            "type": "SOBJ",
            "roomid": 0,
            "layerid": 0
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 16,
            "unk1": "25 5F FF FF",
            "posx": -9681.232421875,
            "posy": 7500.0,
            "posz": 6420.13916015625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "03 8E",
            "talk_behaviour": -181,
            "unk3": "FC 95",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": 10,
            "tosky_scen_link": -1,
            "scen_link": -2,
            "byte4": 0,
            "unk1": "FF 5F FF FF",
            "posx": -9684.443359375,
            "posy": 7500.0,
            "posz": 6852.21875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "22 D8",
            "talk_behaviour": -15499,
            "unk3": "FC 96",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 11,
            "unk1": "FF 1F FF FF",
            "posx": -11953.642578125,
            "posy": 7195.0244140625,
            "posz": 10900.966796875,
            "event_flag": 14,
            "transition_type": -1,
            "unk2": "0C 02",
            "talk_behaviour": -15500,
            "unk3": "FC 97",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 16,
            "unk1": "25 5F FF FF",
            "posx": -9278.5439453125,
            "posy": 7500.0,
            "posz": 6906.681640625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "BF 4A",
            "talk_behaviour": -180,
            "unk3": "FC 9A",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 16,
            "unk1": "25 5F FF FF",
            "posx": -9748.1982421875,
            "posy": 7500.0,
            "posz": 7301.919921875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "74 9F",
            "talk_behaviour": -179,
            "unk3": "FC 9B",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 16,
            "unk1": "25 5F FF FF",
            "posx": -9471.046875,
            "posy": 7500.0,
            "posz": 7194.02783203125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "9B BC",
            "talk_behaviour": -178,
            "unk3": "FC 9C",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -16,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 16,
            "unk1": "25 5F FF FF",
            "posx": -10035.3330078125,
            "posy": 7500.0,
            "posz": 6948.9970703125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "4B 60",
            "talk_behaviour": -177,
            "unk3": "FC 9D",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 0,
            "unk1": "FF 1F FF FF",
            "posx": -10323.5732421875,
            "posy": 7810.0,
            "posz": 6657.39892578125,
            "event_flag": 14,
            "transition_type": 3,
            "unk2": "FF FF",
            "talk_behaviour": -15499,
            "unk3": "FC 9E",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -10223.5732421875,
            "posy": 7810.0,
            "posz": 6657.39892578125,
            "event_flag": 94,
            "transition_type": -1,
            "unk2": "FF 06",
            "talk_behaviour": -15499,
            "unk3": "FC 9F",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11029.0810546875,
            "posy": 7500.0,
            "posz": 6279.25146484375,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "37 77",
            "talk_behaviour": 0,
            "unk3": "FC A0",
            "name": "RuinSav",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 1
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 2
        },
        {
            "byte1": 1,
            "tosky_scen_link": -25,
            "scen_link": -76,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.978515625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15182,
            "unk3": "FC 94",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": 1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 29,
            "unk1": "FF 1F FF FF",
            "posx": -6712.7880859375,
            "posy": 7919.1904296875,
            "posz": 9442.4501953125,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 95",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": 17,
            "tosky_scen_link": -128,
            "scen_link": 39,
            "byte4": -1,
            "unk1": "FF 5F FF 00",
            "posx": -10028.0908203125,
            "posy": 7499.99560546875,
            "posz": 7208.9853515625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "87 D3",
            "talk_behaviour": 0,
            "unk3": "FC 96",
            "name": "NpcRvl",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": 17,
            "tosky_scen_link": -128,
            "scen_link": 39,
            "byte4": 16,
            "unk1": "FF 1F FF FF",
            "posx": -10053.7080078125,
            "posy": 7499.99609375,
            "posz": 6959.11328125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "FF 00",
            "talk_behaviour": -15519,
            "unk3": "FC 97",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 99",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": 1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": 13,
            "unk1": "FF 1F FF FF",
            "posx": -9597.4111328125,
            "posy": 7500.0,
            "posz": 7984.4697265625,
            "event_flag": 73,
            "transition_type": 72,
            "unk2": "FF FF",
            "talk_behaviour": -15179,
            "unk3": "FC 9A",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": -1,
            "tosky_scen_link": -30,
            "scen_link": 15,
            "byte4": 0,
            "unk1": "FF 1F FF FF",
            "posx": -9752.96484375,
            "posy": 7500.0,
            "posz": 7972.50244140625,
            "event_flag": 66,
            "transition_type": -1,
            "unk2": "FF 06",
            "talk_behaviour": -15183,
            "unk3": "FC 9B",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 3
        },
        {
            "byte1": 50,
            "tosky_scen_link": 32,
            "scen_link": 52,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15181,
            "unk3": "FC 94",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 50,
            "unk1": "25 5F FF FF",
            "posx": -9608.3291015625,
            "posy": 7500.0,
            "posz": 7529.1494140625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "78 2D",
            "talk_behaviour": -1,
            "unk3": "FC 95",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 50,
            "unk1": "25 5F FF FF",
            "posx": -8877.7294921875,
            "posy": 7500.0,
            "posz": 7032.8935546875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "BC 72",
            "talk_behaviour": -1,
            "unk3": "FC 96",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 50,
            "unk1": "25 5F FF FF",
            "posx": -9194.783203125,
            "posy": 7500.0,
            "posz": 5943.88623046875,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "DE 94",
            "talk_behaviour": -1,
            "unk3": "FC 97",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 50,
            "unk1": "25 5F FF FF",
            "posx": -9685.4345703125,
            "posy": 7500.0,
            "posz": 6052.29736328125,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "13 33",
            "talk_behaviour": -1,
            "unk3": "FC 98",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -15,
            "tosky_scen_link": -1,
            "scen_link": -103,
            "byte4": 50,
            "unk1": "25 5F FF FF",
            "posx": -10442.3544921875,
            "posy": 7500.0,
            "posz": 7507.56640625,
            "event_flag": -1,
            "transition_type": -1,
            "unk2": "5B BB",
            "talk_behaviour": -1,
            "unk3": "FC 99",
            "name": "EBc",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 9A",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -6712.7880859375,
            "posy": 7919.1904296875,
            "posz": 9442.451171875,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 9B",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": 25,
            "tosky_scen_link": 6,
            "scen_link": 69,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 20,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15181,
            "unk3": "FC 9C",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 4
        },
        {
            "byte1": 50,
            "tosky_scen_link": 35,
            "scen_link": 32,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 94",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": 69,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 20,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 95",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -6712.7880859375,
            "posy": 7919.1904296875,
            "posz": 9442.4501953125,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 96",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 97",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 5
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6
        },
        {
            "byte1": 50,
            "tosky_scen_link": 35,
            "scen_link": 32,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 95",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": 69,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 20,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 96",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -6712.78759765625,
            "posy": 7919.1904296875,
            "posz": 9442.44921875,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 97",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 6
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 7
        },
        {
            "byte1": 50,
            "tosky_scen_link": 35,
            "scen_link": 32,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 95",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 7
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": 69,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 20,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 96",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 7
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -6712.78759765625,
            "posy": 7919.1904296875,
            "posz": 9442.4501953125,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 97",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 7
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 8
        },
        {
            "byte1": 50,
            "tosky_scen_link": 35,
            "scen_link": 32,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 19,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 95",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 8
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": 69,
            "byte4": -13,
            "unk1": "FF 5F FF FF",
            "posx": -6660.97900390625,
            "posy": 7920.0,
            "posz": 9071.54296875,
            "event_flag": 20,
            "transition_type": -1,
            "unk2": "13 E9",
            "talk_behaviour": -15180,
            "unk3": "FC 96",
            "name": "NpcGra",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 8
        },
        {
            "byte1": -1,
            "tosky_scen_link": -26,
            "scen_link": -65,
            "byte4": 22,
            "unk1": "FF 1F FF FF",
            "posx": -6712.78759765625,
            "posy": 7919.1904296875,
            "posz": 9442.451171875,
            "event_flag": 93,
            "transition_type": -1,
            "unk2": "FF 07",
            "talk_behaviour": -15233,
            "unk3": "FC 97",
            "name": "NpcTke",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 8
        },
        {
            "byte1": -7,
            "tosky_scen_link": -18,
            "scen_link": 3,
            "byte4": -1,
            "unk1": "FF FF FF FF",
            "posx": -11143.5,
            "posy": 7500.0,
            "posz": 8236.5,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "E0 00",
            "talk_behaviour": 0,
            "unk3": "FC 94",
            "name": "DmtGate",
            "type": "OBJ ",
            "roomid": 0,
            "layerid": 13
        },
        {
            "byte1": -1,
            "tosky_scen_link": -1,
            "scen_link": -1,
            "byte4": -1,
            "unk1": "FF FF FF F0",
            "posx": -9298.5537109375,
            "posy": 7549.990234375,
            "posz": 8321.1640625,
            "event_flag": 0,
            "transition_type": 0,
            "unk2": "00 00",
            "talk_behaviour": 0,
            "unk3": "FC 00",
            "name": "NpcInv",
            "type": "OBJ ",
            "roomid": 1,
            "layerid": 3
        }
    ]
});